css_SEO = {
    "home": {
        "page_title": "Learn CSS: Syntax, Styling, Selectors, Specificity and Colours",
        "page_description": "Learn CSS fundamentals including CSS syntax, selectors, rules, declarations, adding CSS to HTML, comments, specificity and using colours to style webpages.",
        "schema_type": "TechArticle",
        "slug": "home",
        "section": "CSS",
        "keywords": [
            "CSS",
            "CSS tutorial",
            "CSS syntax",
            "CSS selectors",
            "CSS rules",
            "CSS declarations",
            "CSS specificity",
            "CSS comments",
            "CSS colours",
            "HTML and CSS",
            "web development"
        ],
        "about_name": "CSS Introduction",
        "isPartOf_name": "CSS Tutorial",
    },
    "selectors": {
        "page_title": "CSS Selectors: Simple, Attribute, Combinator and Pseudo Selectors",
        "page_description": "Learn CSS selectors including type, class, ID, attribute and combinator selectors, plus pseudo classes, pseudo elements and CSS inheritance for targeting HTML elements.",
        "schema_type": "TechArticle",
        "slug": "selectors",
        "section": "CSS",
        "keywords": [
            "CSS selectors",
            "CSS selector types",
            "CSS class selectors",
            "CSS ID selectors",
            "CSS attribute selectors",
            "CSS combinator selectors",
            "CSS pseudo classes",
            "CSS pseudo elements",
            "CSS inheritance",
            "CSS tutorial",
            "web development"
        ],
        "about_name": "CSS Selectors",
        "isPartOf_name": "CSS Tutorial",
    },
    "box-model": {
        "page_title": "CSS Box Model Explained: Content, Padding, Border, Margin and Box Sizing",
        "page_description": "Learn the CSS box model including content, padding, border, margin, overflow and box-sizing. Understand how CSS controls element sizing, spacing and webpage layouts.",
        "schema_type": "TechArticle",
        "slug": "box-model",
        "section": "CSS",
        "keywords": [
            "CSS box model",
            "CSS content padding border margin",
            "CSS padding",
            "CSS border",
            "CSS margin",
            "CSS box sizing",
            "CSS overflow",
            "CSS layout",
            "webpage spacing",
            "CSS tutorial",
            "web development"
        ],
        "about_name": "CSS Box Model",
        "isPartOf_name": "CSS Tutorial",
    },
    "display-and-positioning": {
        "page_title": "CSS Display and Positioning: Block, Inline and Layout Control",
        "page_description": "Learn CSS display and positioning properties including block, inline, inline-block, static, relative, absolute, fixed, sticky positioning and vertical alignment.",
        "schema_type": "TechArticle",
        "slug": "display-and-positioning",
        "section": "CSS",
        "keywords": [
            "CSS display property",
            "CSS positioning",
            "CSS block elements",
            "CSS inline elements",
            "CSS inline-block",
            "CSS position property",
            "CSS relative positioning",
            "CSS absolute positioning",
            "CSS fixed positioning",
            "CSS sticky positioning",
            "CSS vertical align",
            "CSS layout",
            "web development"
        ],
        "about_name": "CSS Display and Positioning",
        "isPartOf_name": "CSS Tutorial",
    },
    "flexbox": {
        "page_title": "CSS Flexbox: Flexible Layouts, Alignment and Responsive Design",
        "page_description": "Learn CSS Flexbox including flex containers, flex items, main and cross axes, alignment, wrapping, growth, shrinking and responsive layouts.",
        "schema_type": "TechArticle",
        "slug": "flexbox",
        "section": "CSS",
        "keywords": [
            "CSS Flexbox",
            "CSS flex layout",
            "flexbox tutorial",
            "flex container",
            "flex items",
            "CSS responsive design",
            "CSS layout system",
            "justify-content",
            "align-items",
            "flex-direction",
            "flex-wrap",
            "flex-grow",
            "flex-shrink",
            "flex-basis",
            "frontend development"
        ],
        "about_name": "CSS Flexbox Layout System",
        "isPartOf_name": "CSS Tutorial",
    },
    "grids": {
        "page_title": "CSS Grid Layout: Rows, Columns and Responsive Web Design",
        "page_description": "Learn CSS Grid including grid containers, rows, columns, fractional units, grid gaps, element placement and grid template areas for creating responsive layouts.",
        "schema_type": "TechArticle",
        "slug": "grids",
        "section": "CSS",
        "keywords": [
            "CSS Grid",
            "CSS Grid layout",
            "CSS grid tutorial",
            "CSS responsive layouts",
            "grid container",
            "grid items",
            "CSS rows and columns",
            "grid-template-columns",
            "grid-template-rows",
            "fractional units CSS",
            "fr units",
            "minmax CSS",
            "CSS grid gap",
            "grid-template-areas",
            "frontend development"
        ],
        "about_name": "CSS Grid Layout System",
        "isPartOf_name": "CSS Tutorial",
    },
    "backgrounds": {
        "page_title": "CSS Backgrounds: Colours, Images, Gradients and Styling",
        "page_description": "Learn CSS backgrounds including background colours, images, gradients, sizing, positioning, repetition, attachment and shorthand properties for web design.",
        "schema_type": "TechArticle",
        "slug": "backgrounds",
        "section": "CSS",
        "keywords": [
            "CSS backgrounds",
            "CSS background property",
            "CSS background image",
            "CSS background colour",
            "CSS gradients",
            "background-size",
            "background-position",
            "background-repeat",
            "background-attachment",
            "background shorthand",
            "CSS image backgrounds",
            "web design styling",
            "frontend development"
        ],
        "about_name": "CSS Background Styling",
        "isPartOf_name": "CSS Tutorial",
    },
    "visibility-and-z-positioning": {
        "page_title": "CSS Visibility and Z-Index: Hiding Elements and Managing Layers",
        "page_description": "Learn CSS visibility and z-index including hiding elements, preserving layout space, stacking order, layering elements and creating overlays such as modals.",
        "schema_type": "TechArticle",
        "slug": "visibility-and-z-positioning",
        "section": "CSS",
        "keywords": [
            "CSS visibility",
            "CSS z-index",
            "CSS stacking order",
            "CSS layers",
            "hide elements CSS",
            "visibility hidden",
            "CSS overlays",
            "CSS modal windows",
            "z-index positioning",
            "CSS positioning",
            "frontend development"
        ],
        "about_name": "CSS Visibility and Z-Index",
        "isPartOf_name": "CSS Tutorial",
    },
    "cursor": {
        "page_title": "CSS Cursor Property: Mouse Cursor Styles and Customisation",
        "page_description": "Learn CSS cursor customisation including pointer styles, clickable elements, text selection, dragging, loading states, tooltips and user interface feedback.",
        "schema_type": "TechArticle",
        "slug": "cursor",
        "section": "CSS",
        "keywords": [
            "CSS cursor",
            "CSS cursor property",
            "custom mouse cursor",
            "cursor styles CSS",
            "cursor pointer",
            "CSS hover effects",
            "CSS user interaction",
            "mouse cursor types",
            "CSS UI feedback",
            "frontend development"
        ],
        "about_name": "CSS Cursor Customisation",
        "isPartOf_name": "CSS Tutorial",
    },
    "typography": {
        "page_title": "CSS Typography: Fonts, Text Styling and Web Fonts Explained",
        "page_description": "Learn CSS typography including font families, Google Fonts, custom fonts, text colour, sizing, spacing, alignment, weight, style and decoration.",
        "schema_type": "TechArticle",
        "slug": "typography",
        "section": "CSS",
        "keywords": [
            "CSS typography",
            "CSS fonts",
            "CSS text styling",
            "font-family CSS",
            "font-size CSS",
            "font-weight CSS",
            "font-style CSS",
            "Google Fonts CSS",
            "custom web fonts",
            "@font-face CSS",
            "CSS text alignment",
            "CSS letter spacing",
            "CSS line height",
            "frontend development"
        ],
        "about_name": "CSS Typography and Font Styling",
        "isPartOf_name": "CSS Tutorial",
    },
    "links-and-buttons": {
        "page_title": "CSS Links and Buttons: Styling Interactive Web Elements",
        "page_description": "Learn CSS links and button styling including anchor tag resets, link states, hover effects, active states, cursor changes, and creating interactive button designs.",
        "schema_type": "TechArticle",
        "slug": "links-and-buttons",
        "section": "CSS",
        "keywords": [
            "CSS links",
            "CSS buttons",
            "CSS anchor tags",
            "CSS link styling",
            "CSS remove link underline",
            "CSS text-decoration none",
            "CSS link states",
            "CSS hover effects",
            "CSS visited links",
            "CSS active links",
            "CSS button styling",
            "CSS button hover",
            "CSS button active state",
            "CSS button press effect",
            "CSS box shadow buttons",
            "CSS cursor pointer",
            "frontend development"
        ],
        "about_name": "CSS Links and Button Styling",
        "isPartOf_name": "CSS Tutorial",
    },
    "lists": {
        "page_title": "CSS Lists: Styling HTML Lists with Custom Bullets and Numbers",
        "page_description": "Learn CSS list styling including changing bullet points, numbering styles, custom list images, list positioning, and using the list-style shorthand property.",
        "schema_type": "TechArticle",
        "slug": "lists",
        "section": "CSS",
        "keywords": [
            "CSS lists",
            "CSS list styling",
            "CSS list-style",
            "CSS bullet points",
            "CSS custom bullet points",
            "CSS list-style-type",
            "CSS list-style-image",
            "CSS list-style-position",
            "CSS remove bullet points",
            "CSS ordered list styling",
            "CSS unordered list styling",
            "CSS list shorthand",
            "HTML list styling",
            "frontend development"
        ],
        "about_name": "CSS List Styling and Customisation",
        "isPartOf_name": "CSS Tutorial",
    },
    "forms": {
        "page_title": "CSS Forms: Styling Form Elements with Pseudo Classes",
        "page_description": "Learn CSS form styling using pseudo classes including disabled, enabled, checked, required, optional, valid, and invalid states to create interactive and user-friendly forms.",
        "schema_type": "TechArticle",
        "slug": "forms",
        "section": "CSS",
        "keywords": [
            "CSS forms",
            "CSS form styling",
            "CSS input styling",
            "CSS form elements",
            "CSS pseudo classes",
            "CSS :disabled",
            "CSS :enabled",
            "CSS :checked",
            "CSS :required",
            "CSS :optional",
            "CSS :valid",
            "CSS :invalid",
            "CSS form validation styling",
            "CSS input states",
            "HTML form design",
            "frontend development"
        ],
        "about_name": "CSS Form Styling and Pseudo Classes",
        "isPartOf_name": "CSS Tutorial",
    },
    "transitions": {
        "page_title": "CSS Transitions: Creating Smooth Animations and Hover Effects",
        "page_description": "Learn CSS transitions including transition properties, duration, timing functions, delays, shorthand syntax, and practical examples for creating smooth interactive effects.",
        "schema_type": "TechArticle",
        "slug": "transitions",
        "section": "CSS",
        "keywords": [
            "CSS transitions",
            "CSS animation effects",
            "CSS transition property",
            "CSS transition duration",
            "CSS transition timing function",
            "CSS transition delay",
            "CSS transition shorthand",
            "CSS hover transitions",
            "CSS button animations",
            "CSS image hover effects",
            "CSS ease transition",
            "CSS cubic bezier",
            "CSS transform transitions",
            "frontend development"
        ],
        "about_name": "CSS Transitions and Animation Effects",
        "isPartOf_name": "CSS Tutorial",
        },
    "responsive-design": {
        "page_title": "CSS Responsive Design: Media Queries and Mobile-Friendly Layouts",
        "page_description": "Learn CSS responsive design using media queries, viewport settings, breakpoints, and adaptive styling techniques to create websites that work across different screen sizes and devices.",
        "schema_type": "TechArticle",
        "slug": "responsive-design",
        "section": "CSS",
        "keywords": [
            "CSS responsive design",
            "responsive web design CSS",
            "CSS media queries",
            "CSS breakpoints",
            "mobile responsive CSS",
            "CSS viewport meta tag",
            "CSS min-width",
            "CSS max-width",
            "CSS screen sizes",
            "CSS mobile design",
            "CSS adaptive layouts",
            "responsive website development",
            "CSS em and rem units",
            "frontend development"
        ],
        "about_name": "CSS Responsive Design and Media Queries",
        "isPartOf_name": "CSS Tutorial",
    },
    "bootstrap": {
        "page_title": "CSS Bootstrap: Responsive Grids, Components and Setup Guide",
        "page_description": "Learn how to use Bootstrap CSS including installation, grid layouts, responsive design, hidden elements, and alternatives to Bootstrap.",
        "schema_type": "TechArticle",
        "slug": "bootstrap",
        "section": "CSS",
        "keywords": [
            "Bootstrap CSS",
            "CSS Bootstrap tutorial",
            "Bootstrap setup",
            "Bootstrap grid system",
            "Bootstrap responsive design",
            "Bootstrap columns",
            "Bootstrap rows",
            "Bootstrap breakpoints",
            "Bootstrap responsive classes",
            "Bootstrap hidden elements",
            "Bootstrap CDN",
            "CSS frameworks",
            "frontend development"
        ],
        "about_name": "Bootstrap CSS Framework and Responsive Layouts",
        "isPartOf_name": "CSS Tutorial",
    },
    "css-validation": {
        "page_title": "CSS Validation: W3C Validator and Web Accessibility Testing Guide",
        "page_description": "Learn how to validate CSS code using W3C tools and test website accessibility with validators such as WAVE for better web standards and usability.",
        "schema_type": "TechArticle",
        "slug": "css-validation",
        "section": "CSS",
        "keywords": [
            "CSS validation",
            "W3C CSS validator",
            "CSS code checking",
            "CSS best practices",
            "web accessibility testing",
            "WAVE accessibility validator",
            "HTML accessibility",
            "ARIA labels",
            "colour contrast testing",
            "frontend development"
        ],
        "about_name": "CSS Validation and Web Accessibility Testing",
        "isPartOf_name": "CSS Tutorial",
    },
}