intro_SEO = {
    "programming-and-the-web": {
        "page_title": "Programming and the Web: Declarative vs Imperative Programming",
        "page_description": "Learn the foundations of programming and the web, including declarative and imperative programming paradigms, HTML history, and the origins of the World Wide Web.",
        "schema_type": "TechArticle",
        "slug": "programming-and-the-web",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "programming and the web",
            "declarative programming",
            "imperative programming",
            "programming paradigms",
            "HTML history",
            "history of the World Wide Web",
            "Tim Berners-Lee",
            "HTML introduction",
            "web development fundamentals",
            "frontend development",
            "backend development",
            "HTML markup language",
            "HTTP protocol",
            "software development concepts",
            "full stack development"
        ],
        "about_name": "Programming and the Web",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "github": {
        "page_title": "GitHub and Git Tutorial: Repositories, Commands and Collaboration",
        "page_description": "Learn Git and GitHub fundamentals including repositories, Git commands, commits, GitHub Pages hosting, projects, collaboration, pull requests and version control workflows.",
        "schema_type": "TechArticle",
        "slug": "github",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "GitHub tutorial",
            "Git tutorial",
            "Git version control",
            "GitHub repositories",
            "Git commands",
            "Git commits",
            "Git workflow",
            "GitHub Pages",
            "GitHub Projects",
            "GitHub collaboration",
            "GitHub pull requests",
            "Git merge conflicts",
            "Git branching",
            "forking repositories",
            "software development workflow",
            "developer tools",
            "web development"
        ],
        "about_name": "GitHub and Git",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "vscode": {
        "page_title": "Visual Studio Code Tutorial: Setup, Workspaces and Development",
        "page_description": "Learn how to install and use Visual Studio Code, create workspaces, configure Python, use the terminal and connect GitHub repositories for web development.",
        "schema_type": "TechArticle",
        "slug": "vscode",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "Visual Studio Code tutorial",
            "VS Code setup",
            "VS Code installation",
            "VS Code workspace",
            "code editor",
            "integrated development environment",
            "IDE tutorial",
            "VS Code terminal",
            "VS Code Python setup",
            "Python extension VS Code",
            "GitHub VS Code integration",
            "Git version control",
            "coding tools",
            "web development tools",
            "developer environment",
            "full stack development"
        ],
        "about_name": "Visual Studio Code",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "website-development": {
        "page_title": "Website Development Process: Planning, Coding and Testing",
        "page_description": "Learn the website development process from planning project goals and user stories to writing code, testing, improving accessibility and gathering feedback.",
        "schema_type": "TechArticle",
        "slug": "website-development",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "website development",
            "web development process",
            "website planning",
            "software development lifecycle",
            "project goals",
            "user stories",
            "UI UX design",
            "website features",
            "coding best practices",
            "website testing",
            "web accessibility",
            "website performance",
            "frontend development",
            "backend development",
            "full stack development"
        ],
        "about_name": "Website Development Process",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "sizes": {
        "page_title": "CSS Sizes and Units: Pixels, REM, EM and Viewport Units",
        "page_description": "Learn how website sizing works with CSS units including absolute units, relative units, viewport units, pixels, em, rem, percentages, vw and vh for responsive design.",
        "schema_type": "TechArticle",
        "slug": "sizes",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "CSS sizes",
            "CSS units",
            "CSS absolute units",
            "CSS relative units",
            "CSS viewport units",
            "CSS pixels",
            "CSS px",
            "CSS em",
            "CSS rem",
            "CSS percentages",
            "CSS vw",
            "CSS vh",
            "responsive web design",
            "CSS responsive layouts",
            "frontend development",
            "web development"
        ],
        "about_name": "Website Sizes and CSS Units",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "pseudocode": {
        "page_title": "Pseudocode Guide: Planning Algorithms and Program Logic",
        "page_description": "Learn how to write pseudocode to plan programs, structure algorithms, improve debugging, and organise programming logic before writing code.",
        "schema_type": "TechArticle",
        "slug": "pseudocode",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "pseudocode",
            "pseudocode tutorial",
            "writing algorithms",
            "algorithm planning",
            "programming logic",
            "software development planning",
            "coding best practices",
            "input process output",
            "decision making programming",
            "programming loops",
            "IF ELSE logic",
            "FOR loops",
            "WHILE loops",
            "debugging techniques",
            "full stack development",
            "web development"
        ],
        "about_name": "Pseudocode and Algorithm Planning",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "colour": {
        "page_title": "CSS Colour and Color: Hex, RGB, HSL, Accessibility and Design",
        "page_description": "Learn how colour and color work in web design with CSS formats including hex codes, RGB, RGBA, HSL, HSLA, named colors, colour psychology and accessibility.",
        "schema_type": "TechArticle",
        "slug": "colour",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "CSS colour",
            "CSS color",
            "web design colour",
            "web design color",
            "colour theory web design",
            "color theory web design",
            "hexadecimal colours",
            "hexadecimal colors",
            "hex codes CSS",
            "RGB colours",
            "RGB colors",
            "RGBA colours",
            "RGBA colors",
            "HSL colours",
            "HSL colors",
            "HSLA colours",
            "HSLA colors",
            "CSS named colours",
            "CSS named colors",
            "colour contrast accessibility",
            "color contrast accessibility",
            "WCAG colour contrast",
            "WCAG color contrast",
            "accessible web design",
            "UI colour design",
            "UI color design",
            "website branding",
            "frontend development",
            "web development"
        ],
        "about_name": "Colour and Color in Web Design",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "project-goals": {
        "page_title": "Website Project Goals: Planning User, Owner and Developer Needs",
        "page_description": "Learn how to define website project goals by considering user needs, site owner requirements and developer objectives before starting a web development project.",
        "schema_type": "TechArticle",
        "slug": "project-goals",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "website project goals",
            "web development planning",
            "project requirements",
            "user goals",
            "website owner goals",
            "developer goals",
            "website planning process",
            "UX design planning",
            "user experience goals",
            "responsive web design",
            "website accessibility",
            "secure web development",
            "portfolio website development",
            "software project planning",
            "full stack development",
            "web development"
        ],
        "about_name": "Website Project Goals",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "user-stories": {
        "page_title": "Website User Stories: Planning Features and User Experience",
        "page_description": "Learn how to write website user stories to define features, understand user needs, improve user experience and guide web development projects.",
        "schema_type": "TechArticle",
        "slug": "user-stories",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "website user stories",
            "user stories in web development",
            "UX user stories",
            "user experience planning",
            "website requirements",
            "web development planning",
            "user story syntax",
            "As a user I want to",
            "first time user stories",
            "returning user stories",
            "business owner user stories",
            "website features",
            "software development requirements",
            "agile user stories",
            "full stack development",
            "web development"
        ],
        "about_name": "Website User Stories",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "five-stages": {
        "page_title": "5 Stages of UX/UI Design for Website Development: Strategy, Scope, Structure, Skeleton and Surface",
        "page_description": "Learn the five stages of UX/UI design used in website development: strategy, scope, structure, skeleton and surface. Understand how to plan user needs, project requirements, website features, wireframes, information architecture and visual design before coding.",
        "schema_type": "TechArticle",
        "slug": "five-stages",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "five stages of UX design",
            "UX/UI design process",
            "website UX design",
            "website UI design",
            "web development planning",
            "website development process",
            "strategy scope structure skeleton surface",
            "project planning",
            "website requirements",
            "user experience planning",
            "user interface planning",
            "information architecture",
            "website wireframes",
            "frontend planning",
            "backend planning",
            "database planning",
            "website structure",
            "designing a web application",
            "full stack development",
            "web development"
        ],
        "about_name": "5 Stages of UX/UI Design for Website Development",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "features": {
        "page_title": "Website Features: Planning, Tracking and Documenting Web Development Features",
        "page_description": "Learn how to identify, plan and track website features during development. Understand how features support user requirements, complete user stories and help document the functionality of web projects.",
        "schema_type": "TechArticle",
        "slug": "features",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "website features",
            "web development features",
            "tracking website features",
            "feature documentation",
            "website functionality",
            "web application planning",
            "user stories and features",
            "UX planning",
            "website requirements",
            "frontend features",
            "backend features",
            "development documentation",
            "feature tracking",
            "software development requirements",
            "full stack development",
            "web development"
        ],
        "about_name": "Website Features",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "testing": {
        "page_title": "Website Testing: Manual, Automated, Accessibility and Performance Testing",
        "page_description": "Learn how to test websites during development using manual testing, automated testing, browser and device testing, accessibility testing, performance testing and bug tracking to ensure a reliable user experience.",
        "schema_type": "TechArticle",
        "slug": "testing",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "website testing",
            "web development testing",
            "manual testing",
            "automated testing",
            "browser testing",
            "device testing",
            "accessibility testing",
            "performance testing",
            "website bug tracking",
            "software testing",
            "user testing",
            "regression testing",
            "test driven development",
            "TDD web development",
            "WCAG accessibility testing",
            "website quality assurance",
            "full stack development",
            "web development"
        ],
        "about_name": "Website Testing",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "google-dev-tools": {
        "page_title": "Google Chrome DevTools: Inspect, Debug and Optimise Websites",
        "page_description": "Learn how to use Google Chrome DevTools to inspect HTML and CSS, debug JavaScript, analyse website performance, test accessibility and optimise web applications during development.",
        "schema_type": "TechArticle",
        "slug": "google-dev-tools",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "Google DevTools",
            "Chrome DevTools",
            "web development tools",
            "inspect HTML and CSS",
            "debug JavaScript",
            "browser developer tools",
            "Chrome developer tools",
            "DevTools Elements panel",
            "DevTools Console",
            "Lighthouse testing",
            "website performance testing",
            "accessibility testing tools",
            "frontend debugging",
            "web application optimisation",
            "full stack development",
            "web development"
        ],
        "about_name": "Google Chrome DevTools",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
    "readme": {
        "page_title": "README.md Guide: Creating Professional GitHub Project Documentation",
        "page_description": "Learn how to create a professional README.md file for GitHub projects including project goals, user stories, security, technologies, testing, deployment and documentation.",
        "schema_type": "TechArticle",
        "slug": "readme",
        "section": "Introduction to Full Stack Development",
        "keywords": [
            "README.md file",
            "GitHub README",
            "GitHub project documentation",
            "markdown documentation",
            "software documentation",
            "web development portfolio",
            "project documentation template",
            "README sections",
            "DESIGN.md",
            "TESTING.md",
            "DEV.md",
            "GitHub repository documentation",
            "full stack development"
        ],
        "about_name": "README.md Documentation",
        "isPartOf_name": "Introduction to Full Stack Development",
    },
}