from django.urls import path
from . import views


urlpatterns = [
    path(
        'programming-and-the-web/',
        views.full_stack_programming_and_the_web,
        name="full_stack_programming_and_the_web"
    ),
    path(
        'github/',
        views.full_stack_github,
        name="full_stack_github"
    ),
    path(
        'website-development/',
        views.full_stack_website_development,
        name="full_stack_website_development"
    ),
    path(
        'sizes/',
        views.full_stack_sizes,
        name="full_stack_sizes"
    ),
    path(
        'colour/',
        views.full_stack_colour,
        name="full_stack_colour"
    ),
    path(
        'project-goals/',
        views.full_stack_project_goals,
        name="full_stack_project_goals"
    ),
    path(
        'user-stories/',
        views.full_stack_user_stories,
        name="full_stack_user_stories"
    ),
    path(
        'five-stages/',
        views.full_stack_five_stages,
        name="full_stack_five_stages"
    ),
    path(
        'features/',
        views.full_stack_features,
        name="full_stack_features"
    ),
    path(
        'testing/',
        views.full_stack_testing,
        name="full_stack_testing"
    ),
    path(
        'google-dev-tools/',
        views.full_stack_google_dev_tools,
        name="full_stack_google_dev_tools"
    ),
    path(
        'readme/',
        views.full_stack_readme,
        name="full_stack_readme"
    ),
    path(
        'vscode/',
        views.full_stack_vscode,
        name="full_stack_vscode"
    ),
    path(
        'pseudocode/',
        views.full_stack_pseudocode,
        name="full_stack_pseudocode"
    ),
]
