flask_SEO = {
    "home": {
        "page_title": "Learn Flask: Python Microframework Introduction",
        "page_description": "Learn Flask fundamentals including what Flask is, Jinja2 templating, URL routing, WSGI, and how to structure a Flask application using PostgreSQL.",
        "schema_type": "TechArticle",
        "slug": "home",
        "section": "Flask",
        "keywords": [
            "Flask",
            "Flask tutorial",
            "Python Flask",
            "Flask microframework",
            "Flask routing",
            "Jinja2",
            "Flask templates",
            "WSGI",
            "Flask PostgreSQL",
            "Flask application",
            "Python web framework",
            "web development"
        ],
        "about_name": "Flask Introduction",
        "isPartOf_name": "Flask Tutorial",
    },
    "basics": {
        "page_title": "Flask Setup Guide: Create Your First Flask Project",
        "page_description": "Learn how to set up a Flask project from scratch with a virtual environment, SQLAlchemy, PostgreSQL, routes, templates, environment variables and project structure.",
        "schema_type": "TechArticle",
        "slug": "basics",
        "section": "Flask",
        "keywords": [
            "Flask setup",
            "Flask tutorial",
            "Flask project structure",
            "Flask virtual environment",
            "Flask SQLAlchemy",
            "PostgreSQL Flask",
            "psycopg2",
            "Flask routes",
            "Flask templates",
            "Flask __init__.py",
            "Flask run.py",
            "Flask env.py",
            "Flask configuration",
            "Python Flask guide",
            "Python web development"
        ],
        "about_name": "Setting Up a Flask Project",
        "isPartOf_name": "Flask Tutorial",
    },
    "database": {
        "page_title": "Flask Database Tutorial: SQLAlchemy Models & PostgreSQL",
        "page_description": "Learn how to create SQLAlchemy models, define relationships, configure PostgreSQL, update your database and connect Flask models using SQLAlchemy ORM.",
        "schema_type": "TechArticle",
        "slug": "database",
        "section": "Flask",
        "keywords": [
            "Flask database",
            "Flask SQLAlchemy",
            "SQLAlchemy models",
            "Flask models",
            "PostgreSQL Flask",
            "Flask ORM",
            "SQLAlchemy relationships",
            "Flask foreign keys",
            "Flask database tutorial",
            "Flask create database",
            "Flask PostgreSQL setup",
            "db.relationship",
            "db.ForeignKey",
            "Flask create_all",
            "Python database tutorial",
            "web development"
        ],
        "about_name": "Creating a Flask Database with SQLAlchemy",
        "isPartOf_name": "Flask Tutorial",
    },
    "template": {
        "page_title": "Flask Template Inheritance with Jinja2: Base Templates and Blocks",
        "page_description": "Learn Flask template inheritance using Jinja2, including base.html layouts, extends, includes, blocks, conditionals, loops and url_for routing for reusable web templates.",
        "schema_type": "TechArticle",
        "slug": "template",
        "section": "Flask",
        "keywords": [
            "Flask template inheritance",
            "Flask templates",
            "Jinja2 templates",
            "Flask Jinja2",
            "base.html Flask",
            "Flask extends",
            "Flask include",
            "Jinja blocks",
            "Jinja if statements",
            "Jinja for loops",
            "url_for Flask",
            "Flask dynamic HTML",
            "Flask frontend development",
            "reusable templates",
            "DRY code Flask",
            "web development"
        ],
        "about_name": "Flask Template Inheritance",
        "isPartOf_name": "Flask Tutorial",
    },
    "create": {
        "page_title": "Flask Create Records: Forms, Routes and Database Updates",
        "page_description": "Learn how to create records in Flask using templates, routes, HTML forms, POST requests and SQLAlchemy database updates with practical examples.",
        "schema_type": "TechArticle",
        "slug": "create",
        "section": "Flask",
        "keywords": [
            "Flask create records",
            "Flask forms",
            "Flask POST requests",
            "Flask routing",
            "Flask templates",
            "Flask template inheritance",
            "Jinja2 forms",
            "Flask SQLAlchemy",
            "Flask database updates",
            "Flask request form data",
            "Flask redirect",
            "Flask url_for",
            "HTML forms Flask",
            "CRUD operations Flask",
            "Flask CRUD tutorial",
            "web development"
        ],
        "about_name": "Creating Records in Flask",
        "isPartOf_name": "Flask Tutorial",
    },
    "read": {
        "page_title": "Flask Read Records: Querying Databases and Displaying Data",
        "page_description": "Learn how to read database records in Flask using SQLAlchemy queries, routes, render_template, and Jinja2 templates to display dynamic data.",
        "schema_type": "TechArticle",
        "slug": "read",
        "section": "Flask",
        "keywords": [
            "Flask read records",
            "Flask database queries",
            "Flask SQLAlchemy query",
            "Flask models",
            "Flask routes",
            "Flask render_template",
            "Jinja2 variables",
            "Jinja2 loops",
            "Flask display database data",
            "SQLAlchemy filter_by",
            "SQLAlchemy first",
            "Flask CRUD operations",
            "Flask database tutorial",
            "dynamic HTML Flask",
            "web development"
        ],
        "about_name": "Reading Records in Flask",
        "isPartOf_name": "Flask Tutorial",
    },
    "update": {
        "page_title": "Flask Update Records: Editing Database Data with Forms",
        "page_description": "Learn how to update database records in Flask using routes, forms, SQLAlchemy queries, Jinja2 templates, and POST requests to edit existing data.",
        "schema_type": "TechArticle",
        "slug": "update",
        "section": "Flask",
        "keywords": [
            "Flask update records",
            "Flask edit records",
            "Flask update database",
            "Flask forms",
            "Flask POST requests",
            "Flask routes",
            "Flask SQLAlchemy update",
            "SQLAlchemy get_or_404",
            "Jinja2 templates",
            "Flask CRUD update",
            "Flask CRUD operations",
            "Flask database editing",
            "Flask dynamic routes",
            "Flask URL parameters",
            "web development"
        ],
        "about_name": "Updating Records in Flask",
        "isPartOf_name": "Flask Tutorial",
    },
    "delete": {
        "page_title": "Flask Delete Records: Removing Data Safely with SQLAlchemy",
        "page_description": "Learn how to delete database records in Flask using SQLAlchemy, routes, URL parameters, redirects and defensive programming techniques to prevent accidental data loss.",
        "schema_type": "TechArticle",
        "slug": "delete",
        "section": "Flask",
        "keywords": [
            "Flask delete records",
            "Flask delete database data",
            "Flask SQLAlchemy delete",
            "Flask CRUD delete",
            "Flask routes",
            "Flask URL parameters",
            "SQLAlchemy get_or_404",
            "Flask database management",
            "Flask redirect",
            "Flask defensive programming",
            "Flask delete confirmation",
            "Flask user permissions",
            "Flask session authentication",
            "Prevent accidental deletion Flask",
            "web development"
        ],
        "about_name": "Deleting Records in Flask",
        "isPartOf_name": "Flask Tutorial",
    },
}