javascript_SEO = {
    "home": {
        "page_title": "Learn JavaScript: Syntax, Asynchrony, Running Code and Web Interactivity",
        "page_description": "Learn JavaScript fundamentals including what JavaScript is, how to run JavaScript locally, asynchronous programming, syntax rules, comments, variables, functions and best practices for web development.",
        "schema_type": "TechArticle",
        "slug": "home",
        "section": "JavaScript",
        "keywords": [
            "JavaScript",
            "JavaScript programming",
            "JavaScript tutorial",
            "learn JavaScript",
            "JavaScript syntax",
            "JavaScript basics",
            "JavaScript for web development",
            "frontend JavaScript",
            "JavaScript interactivity",
            "JavaScript animations",
            "JavaScript visual effects",
            "running JavaScript locally",
            "Node.js JavaScript",
            "JavaScript asynchronous programming",
            "JavaScript asynchrony",
            "JavaScript event loop",
            "JavaScript comments",
            "JavaScript variables",
            "JavaScript functions",
            "JavaScript camel case",
            "JavaScript arrays",
            "JavaScript best practices",
            "Mozilla JavaScript documentation",
            "full stack development",
            "web development"
        ],
        "about_name": "JavaScript Fundamentals",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "variables": {
        "page_title": "JavaScript Variables: Declaring, Naming and Updating Values",
        "page_description": "Learn how JavaScript variables work including naming conventions, let, const, var, declaring variables, reassigning values and storing data for web development.",
        "schema_type": "TechArticle",
        "slug": "variables",
        "section": "JavaScript",
        "keywords": [
            "JavaScript variables",
            "variables in JavaScript",
            "JavaScript let",
            "JavaScript const",
            "JavaScript var",
            "declaring variables",
            "reassigning variables",
            "updating JavaScript variables",
            "JavaScript variable naming",
            "camel case JavaScript",
            "JavaScript naming conventions",
            "JavaScript reserved words",
            "JavaScript basics",
            "JavaScript programming",
            "learn JavaScript",
            "frontend development",
            "web development",
            "full stack development"
        ],
        "about_name": "JavaScript Variables",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "scope": {
        "page_title": "JavaScript Scope: Global Scope, Block Scope and Variable Access",
        "page_description": "Learn JavaScript scope including global variables, block scope, local variables, functions and how scope controls where variables can be accessed.",
        "schema_type": "TechArticle",
        "slug": "scope",
        "section": "JavaScript",
        "keywords": [
            "JavaScript scope",
            "JavaScript block scope",
            "global scope JavaScript",
            "local variables JavaScript",
            "variable accessibility",
            "ReferenceError JavaScript",
            "JavaScript functions",
            "let scope",
            "const scope",
            "JavaScript fundamentals",
            "web development"
        ],
        "about_name": "JavaScript Scope",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "data-types": {
        "page_title": "JavaScript Data Types: Numbers, Strings, Objects, Booleans and Type Conversion",
        "page_description": "Learn JavaScript data types including numbers, BigInt, strings, booleans, objects, null, undefined, operators and converting between different data types.",
        "schema_type": "TechArticle",
        "slug": "data-types",
        "section": "JavaScript",
        "keywords": [
            "JavaScript data types",
            "JavaScript number type",
            "JavaScript strings",
            "JavaScript booleans",
            "JavaScript objects",
            "JavaScript BigInt",
            "JavaScript null",
            "JavaScript undefined",
            "JavaScript operators",
            "JavaScript type conversion",
            "JavaScript type coercion",
            "typeof JavaScript",
            "JavaScript methods",
            "frontend programming",
            "web development"
        ],
        "about_name": "JavaScript Data Types",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "math": {
        "page_title": "JavaScript Math Object: Mathematical Methods and Calculations",
        "page_description": "Learn how to use the JavaScript Math global object including common mathematical methods for rounding, random numbers, powers, logarithms, trigonometry and calculations.",
        "schema_type": "TechArticle",
        "slug": "math",
        "section": "JavaScript",
        "keywords": [
            "JavaScript Math object",
            "JavaScript mathematical methods",
            "Math.random JavaScript",
            "Math.round JavaScript",
            "Math.floor JavaScript",
            "Math.sqrt JavaScript",
            "Math.pow JavaScript",
            "JavaScript calculations",
            "JavaScript numbers",
            "JavaScript built in objects",
            "frontend programming",
            "web development"
        ],
        "about_name": "JavaScript Math Object",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "arrays": {
        "page_title": "JavaScript Arrays: Creating, Modifying and Manipulating Data Collections",
        "page_description": "Learn JavaScript arrays including creating arrays, accessing elements, iterating through data, nested arrays, spread and rest operators, destructuring assignment and common array methods.",
        "schema_type": "TechArticle",
        "slug": "arrays",
        "section": "JavaScript",
        "keywords": [
            "JavaScript arrays",
            "JavaScript array methods",
            "creating arrays JavaScript",
            "array indexing JavaScript",
            "iterating arrays",
            "nested arrays",
            "spread operator JavaScript",
            "rest operator JavaScript",
            "destructuring assignment JavaScript",
            "array push pop methods",
            "array map filter reduce",
            "JavaScript data structures",
            "frontend programming",
            "web development"
        ],
        "about_name": "JavaScript Arrays",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "sets": {
        "page_title": "JavaScript Sets: Storing Unique Values and Managing Collections",
        "page_description": "Learn JavaScript Sets including creating sets, storing unique values, checking values, adding and removing elements and using built-in Set methods.",
        "schema_type": "TechArticle",
        "slug": "sets",
        "section": "JavaScript",
        "keywords": [
            "JavaScript Sets",
            "JavaScript Set object",
            "unique values JavaScript",
            "Set methods JavaScript",
            "creating Sets",
            "Set add method",
            "Set delete method",
            "Set has method",
            "Set clear method",
            "JavaScript collections",
            "arrays vs sets JavaScript",
            "frontend programming",
            "web development"
        ],
        "about_name": "JavaScript Sets",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "objects": {
        "page_title": "JavaScript Objects: Properties, Methods, Constructors and Getters",
        "page_description": "Learn JavaScript objects including object literals, properties, methods, constructor and factory functions, nested objects, looping, getters and setters.",
        "schema_type": "TechArticle",
        "slug": "objects",
        "section": "JavaScript",
        "keywords": [
            "JavaScript objects",
            "JavaScript object properties",
            "JavaScript object methods",
            "JavaScript object literals",
            "JavaScript constructor functions",
            "JavaScript factory functions",
            "JavaScript nested objects",
            "JavaScript object loops",
            "JavaScript getters and setters",
            "JavaScript Object methods",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript Objects",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "console-commands": {
        "page_title": "JavaScript Console Commands: Log, Debug and Inspect Code",
        "page_description": "Learn JavaScript console commands including console.log(), console.table(), console.error(), console.warn(), console.info(), and debugging techniques.",
        "schema_type": "TechArticle",
        "slug": "console-commands",
        "section": "JavaScript",
        "keywords": [
            "JavaScript console commands",
            "JavaScript console.log",
            "JavaScript console.table",
            "JavaScript console methods",
            "JavaScript debugging",
            "JavaScript developer tools",
            "JavaScript console error",
            "JavaScript console warning",
            "JavaScript console.info",
            "JavaScript console.group",
            "browser console",
            "Node.js console",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript Console Commands",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "functions": {
        "page_title": "JavaScript Functions: Parameters, Returns, Arrow Functions and More",
        "page_description": "Learn JavaScript functions including defining functions, parameters, arguments, return values, helper functions, arrow functions and best practices.",
        "schema_type": "TechArticle",
        "slug": "functions",
        "section": "JavaScript",
        "keywords": [
            "JavaScript functions",
            "JavaScript function syntax",
            "JavaScript parameters",
            "JavaScript arguments",
            "JavaScript return values",
            "JavaScript arrow functions",
            "JavaScript helper functions",
            "JavaScript function expressions",
            "JavaScript docstrings",
            "JavaScript default parameters",
            "JavaScript arrays and functions",
            "JavaScript ES6 functions",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript Functions",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "conditional-statements": {
        "page_title": "JavaScript Conditional Statements: If, Else, Ternary and Switch",
        "page_description": "Learn JavaScript conditional statements including if, else if, else, ternary operators, comparison operators, truthy values and switch statements.",
        "schema_type": "TechArticle",
        "slug": "conditional-statements",
        "section": "JavaScript",
        "keywords": [
            "JavaScript conditional statements",
            "JavaScript if statement",
            "JavaScript else if",
            "JavaScript else statement",
            "JavaScript ternary operator",
            "JavaScript comparison operators",
            "JavaScript strict equality",
            "JavaScript truthy and falsy values",
            "JavaScript switch statement",
            "JavaScript logical operators",
            "JavaScript control flow",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript Conditional Statements",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "for-loops": {
        "page_title": "JavaScript For Loops: For, For In and For Of Loops",
        "page_description": "Learn JavaScript loops including for loops, for...in, for...of, loop syntax, counters, iterables, and how to repeat code efficiently.",
        "schema_type": "TechArticle",
        "slug": "for-loops",
        "section": "JavaScript",
        "keywords": [
            "JavaScript for loops",
            "JavaScript for loop syntax",
            "JavaScript for in loop",
            "JavaScript for of loop",
            "JavaScript loops tutorial",
            "JavaScript iteration",
            "JavaScript iterable objects",
            "JavaScript object loops",
            "JavaScript array loops",
            "JavaScript loop counter",
            "JavaScript increment operator",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript For Loops",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "while-loops": {
        "page_title": "JavaScript While Loops: Do While, Break and Continue",
        "page_description": "Learn JavaScript while loops including while, do...while, break, continue, loop conditions and how to repeat code when iterations are unknown.",
        "schema_type": "TechArticle",
        "slug": "while-loops",
        "section": "JavaScript",
        "keywords": [
            "JavaScript while loops",
            "JavaScript do while loop",
            "JavaScript break statement",
            "JavaScript continue statement",
            "JavaScript loop conditions",
            "JavaScript iteration",
            "JavaScript control flow",
            "JavaScript repeating code",
            "JavaScript loops tutorial",
            "JavaScript beginner tutorial",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript While Loops",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "try": {
        "page_title": "JavaScript Try Catch: Error Handling and Throw Statements",
        "page_description": "Learn JavaScript error handling with try...catch, finally, built-in error types, instanceof checks and creating custom errors with throw.",
        "schema_type": "TechArticle",
        "slug": "try",
        "section": "JavaScript",
        "keywords": [
            "JavaScript try catch",
            "JavaScript error handling",
            "JavaScript throw statement",
            "JavaScript finally block",
            "JavaScript errors",
            "JavaScript Error object",
            "JavaScript TypeError",
            "JavaScript SyntaxError",
            "JavaScript RangeError",
            "JavaScript custom errors",
            "JavaScript debugging",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript Error Handling",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "nested-loops": {
        "page_title": "JavaScript Nested Loops: Loops Inside Loops and Labels",
        "page_description": "Learn JavaScript nested loops including loops inside loops, working with multidimensional data, labelled loops, break and continue control.",
        "schema_type": "TechArticle",
        "slug": "nested-loops",
        "section": "JavaScript",
        "keywords": [
            "JavaScript nested loops",
            "JavaScript loops inside loops",
            "JavaScript labelled loops",
            "JavaScript break label",
            "JavaScript continue label",
            "JavaScript multidimensional arrays",
            "JavaScript loop control",
            "JavaScript iteration",
            "JavaScript for loops",
            "JavaScript programming tutorial",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript Nested Loops",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "the-dom": {
        "page_title": "JavaScript DOM: Document Object Model Explained",
        "page_description": "Learn the JavaScript DOM (Document Object Model), how HTML elements form a tree structure, and how JavaScript interacts with webpages.",
        "schema_type": "TechArticle",
        "slug": "the-dom",
        "section": "JavaScript",
        "keywords": [
            "JavaScript DOM",
            "Document Object Model",
            "JavaScript HTML manipulation",
            "DOM tree",
            "HTML elements hierarchy",
            "JavaScript webpage interaction",
            "JavaScript document object",
            "DOM elements",
            "JavaScript tutorial",
            "web development",
            "frontend development"
        ],
        "about_name": "JavaScript Document Object Model (DOM)",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "targeting-the-dom": {
        "page_title": "JavaScript DOM Manipulation: Select and Control Elements",
        "page_description": "Learn JavaScript DOM manipulation including window objects, document selectors, elements, URL handling, storage, and navigating the DOM tree.",
        "schema_type": "TechArticle",
        "slug": "targeting-the-dom",
        "section": "JavaScript",
        "keywords": [
            "JavaScript DOM manipulation",
            "JavaScript document object",
            "JavaScript window object",
            "JavaScript querySelector",
            "JavaScript getElementById",
            "JavaScript getElementsByClassName",
            "JavaScript DOM selectors",
            "JavaScript localStorage",
            "JavaScript window location",
            "JavaScript browser APIs",
            "JavaScript HTML elements",
            "JavaScript parent and child elements",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript DOM Manipulation",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "manipulating-the-dom": {
        "page_title": "JavaScript DOM Manipulation: Create, Edit and Update HTML",
        "page_description": "Learn JavaScript DOM manipulation including changing HTML content, element properties, creating elements, adding classes, and updating webpages dynamically.",
        "schema_type": "TechArticle",
        "slug": "manipulating-the-dom",
        "section": "JavaScript",
        "keywords": [
            "JavaScript DOM manipulation",
            "JavaScript create elements",
            "JavaScript update HTML",
            "JavaScript change HTML content",
            "JavaScript innerHTML",
            "JavaScript createElement",
            "JavaScript appendChild",
            "JavaScript classList",
            "JavaScript element properties",
            "JavaScript remove elements",
            "JavaScript cloneNode",
            "JavaScript dynamic webpages",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript DOM Manipulation",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "events": {
        "page_title": "JavaScript Events: Event Listeners, Handlers and DOM Events",
        "page_description": "Learn JavaScript events including mouse, keyboard, form, window and clipboard events, event listeners, bubbling, and handling user interactions.",
        "schema_type": "TechArticle",
        "slug": "events",
        "section": "JavaScript",
        "keywords": [
            "JavaScript events",
            "JavaScript event listeners",
            "JavaScript event handlers",
            "JavaScript addEventListener",
            "JavaScript mouse events",
            "JavaScript keyboard events",
            "JavaScript form events",
            "JavaScript window events",
            "JavaScript event bubbling",
            "JavaScript DOM events",
            "JavaScript preventDefault",
            "JavaScript event object",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript Events",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "jquery": {
        "page_title": "jQuery Tutorial: Selectors, DOM Manipulation and Events",
        "page_description": "Learn jQuery including setup, element selectors, DOM manipulation, event handling, animations, effects, AJAX, and common jQuery methods.",
        "schema_type": "TechArticle",
        "slug": "jquery",
        "section": "JavaScript",
        "keywords": [
            "jQuery tutorial",
            "JavaScript jQuery library",
            "jQuery selectors",
            "jQuery DOM manipulation",
            "jQuery events",
            "jQuery addClass",
            "jQuery removeClass",
            "jQuery animations",
            "jQuery effects",
            "jQuery AJAX",
            "jQuery method chaining",
            "jQuery syntax",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "jQuery JavaScript Library",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "debugging": {
        "page_title": "JavaScript Debugging: DevTools, Breakpoints and Debugger",
        "page_description": "Learn JavaScript debugging using browser DevTools, debugger statements, breakpoints, stepping through code, and inspecting variables.",
        "schema_type": "TechArticle",
        "slug": "debugging",
        "section": "JavaScript",
        "keywords": [
            "JavaScript debugging",
            "JavaScript DevTools",
            "JavaScript debugger statement",
            "JavaScript breakpoints",
            "browser developer tools",
            "JavaScript inspect variables",
            "JavaScript step over",
            "JavaScript step into",
            "JavaScript step out",
            "JavaScript debugging tutorial",
            "JavaScript error fixing",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript Debugging",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "validation": {
        "page_title": "JavaScript Validation: Linters, Forms and Validation Libraries",
        "page_description": "Learn JavaScript validation including checking data, code linters, ESLint alternatives, and using validation libraries for forms.",
        "schema_type": "TechArticle",
        "slug": "validation",
        "section": "JavaScript",
        "keywords": [
            "JavaScript validation",
            "JavaScript form validation",
            "JavaScript data validation",
            "JavaScript code linters",
            "JavaScript JSLint",
            "JavaScript ESLint",
            "JavaScript JSHint",
            "JavaScript validation libraries",
            "just-validate JavaScript",
            "client side validation",
            "JavaScript best practices",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "JavaScript Validation",
        "isPartOf_name": "JavaScript Tutorial",
    },
    "emailjs": {
        "page_title": "EmailJS JavaScript Forms: Send Emails Without a Backend",
        "page_description": "Learn how to use EmailJS with JavaScript forms to send emails from static websites using templates, services, public keys, and form handling.",
        "schema_type": "TechArticle",
        "slug": "emailjs",
        "section": "JavaScript",
        "keywords": [
            "EmailJS JavaScript",
            "JavaScript email forms",
            "JavaScript contact forms",
            "Send emails with JavaScript",
            "EmailJS setup tutorial",
            "EmailJS templates",
            "EmailJS service ID",
            "EmailJS public key",
            "JavaScript form submission",
            "JavaScript static website forms",
            "client side email sending",
            "JavaScript tutorial",
            "web development"
        ],
        "about_name": "EmailJS JavaScript Integration",
        "isPartOf_name": "JavaScript Tutorial",
    },
}