from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.JavaScript_home, name="JavaScript_home"),
    path(
        'variables/',
        views.JavaScript_variables,
        name="JavaScript_variables"
    ),
    path(
        'scope/',
        views.JavaScript_scope,
        name="JavaScript_scope"
    ),
    path(
        'data-types/',
        views.JavaScript_data_types,
        name="JavaScript_data_types"
    ),
    path(
        'math/',
        views.JavaScript_math,
        name="JavaScript_math"
    ),
    path(
        'arrays/',
        views.JavaScript_arrays,
        name="JavaScript_arrays"
    ),
    path(
        'sets/',
        views.JavaScript_sets,
        name="JavaScript_sets"
    ),
    path(
        'objects/',
        views.JavaScript_objects,
        name="JavaScript_objects"
    ),
    path(
        'console-commands/',
        views.JavaScript_console_commands,
        name="JavaScript_console_commands"
    ),
    path(
        'functions/',
        views.JavaScript_functions,
        name="JavaScript_functions"
    ),
    path(
        'conditional-statements/',
        views.JavaScript_conditional_statements,
        name="JavaScript_conditional_statements"
    ),
    path(
        'for-loops/',
        views.JavaScript_for_loops,
        name="JavaScript_for_loops"
    ),
    path(
        'while-loops/',
        views.JavaScript_while_loops,
        name="JavaScript_while_loops"
    ),
    path(
        'try/',
        views.JavaScript_try,
        name="JavaScript_try"
    ),
    path(
        'nested-loops/',
        views.JavaScript_nested_loops,
        name="JavaScript_nested_loops"
    ),
    path(
        'the-dom/',
        views.JavaScript_the_dom,
        name="JavaScript_the_dom"
    ),
    path(
        'targeting-the-dom/',
        views.JavaScript_targeting_the_dom,
        name="JavaScript_targeting_the_dom"
    ),
    path(
        'manipulating-the-dom/',
        views.JavaScript_manipulating_the_dom,
        name="JavaScript_manipulating_the_dom"
    ),
    path(
        'events/',
        views.JavaScript_events,
        name="JavaScript_events"
    ),
    path(
        'jquery/',
        views.JavaScript_jquery,
        name="JavaScript_jquery"
    ),
    path(
        'debugging/',
        views.JavaScript_debugging,
        name="JavaScript_debugging"
    ),
    path(
        'validation/',
        views.JavaScript_validation,
        name="JavaScript_validation"
    ),
]
