from django.urls import path
from . import views


urlpatterns = [
    path('', views.JavaScript_home, name="JavaScript_home"),
    path(
        'variables/',
        views.JavaScript_variables,
        name="JavaScript_variables"
    ),
    path(
        'scope/',
        views.JavaScript_scope,
        name="JavaScript_scope"
    ),
    path(
        'data_types/',
        views.JavaScript_data_types,
        name="JavaScript_data_types"
    ),
    path(
        'math/',
        views.JavaScript_math,
        name="JavaScript_math"
    ),
    path(
        'arrays/',
        views.JavaScript_arrays,
        name="JavaScript_arrays"
    ),
    path(
        'sets/',
        views.JavaScript_sets,
        name="JavaScript_sets"
    ),
    path(
        'objects/',
        views.JavaScript_objects,
        name="JavaScript_objects"
    ),
    path(
        'console/',
        views.JavaScript_console,
        name="JavaScript_console"
    ),
    path(
        'functions/',
        views.JavaScript_functions,
        name="JavaScript_functions"
    ),
    path(
        'conditional_statements/',
        views.JavaScript_conditional_statements,
        name="JavaScript_conditional_statements"
    ),
    path(
        'for_loops/',
        views.JavaScript_for_loops,
        name="JavaScript_for_loops"
    ),
    path(
        'while_loops/',
        views.JavaScript_while_loops,
        name="JavaScript_while_loops"
    ),
    path(
        'try/',
        views.JavaScript_try,
        name="JavaScript_try"
    ),
    path(
        'nested_loops/',
        views.JavaScript_nested_loops,
        name="JavaScript_nested_loops"
    ),
    path(
        'the_dom/',
        views.JavaScript_the_dom,
        name="JavaScript_the_dom"
    ),
]
