backend_SEO = {
    "home": {
        "page_title": "Back-End Development: Databases, DBMS, Queries and Data Storage",
        "page_description": "Learn back-end development fundamentals including databases, DBMS, queries, tables, schemas, relational databases and non-relational databases.",
        "schema_type": "TechArticle",
        "slug": "home",
        "section": "Backend",
        "keywords": [
            "backend development",
            "back-end programming",
            "web application backend",
            "databases",
            "database management system",
            "DBMS",
            "relational databases",
            "non-relational databases",
            "SQL databases",
            "database schema"
        ],
        "about_name": "Backend Development",
        "isPartOf_name": "Backend Development Tutorial",
    },
    "databases": {
        "page_title": "Relational and Non-Relational Databases: SQL vs NoSQL Explained",
        "page_description": "Learn the differences between relational and non-relational databases, including SQL, NoSQL, tables, documents, schemas, relationships, scalability and database structures.",
        "schema_type": "TechArticle",
        "slug": "databases",
        "section": "Backend",
        "keywords": [
            "relational databases",
            "non-relational databases",
            "SQL databases",
            "NoSQL databases",
            "SQL vs NoSQL",
            "database models",
            "database schema",
            "MongoDB databases",
            "database tables and documents",
            "backend development"
        ],
        "about_name": "Relational and Non-Relational Databases",
        "isPartOf_name": "Backend Development Tutorial",
    },
    "designing-a-database": {
        "page_title": "Designing a Database: Data Models, ERDs and Database Planning",
        "page_description": "Learn how to design a database using data models, entity relationship diagrams, database entities, attributes, relationships, primary keys, foreign keys and normalisation.",
        "schema_type": "TechArticle",
        "slug": "designing-a-database",
        "section": "Backend",
        "keywords": [
            "database design",
            "data models",
            "entity relationship diagrams",
            "ERD",
            "database schema design",
            "database entities",
            "primary keys",
            "foreign keys",
            "database normalisation",
            "backend development"
        ],
        "about_name": "Database Design and ERDs",
        "isPartOf_name": "Backend Development Tutorial",
    },
    "sql": {
        "page_title": "SQL Basics: Queries, Syntax and Database Commands",
        "page_description": "Learn SQL fundamentals including queries, SELECT statements, filtering, grouping, joins, aggregates and common database commands.",
        "schema_type": "TechArticle",
        "slug": "sql",
        "section": "Backend",
        "keywords": [
            "SQL",
            "SQL queries",
            "SQL syntax",
            "SELECT statement",
            "SQL filtering",
            "SQL joins",
            "SQL aggregate functions",
            "CRUD SQL",
            "relational databases",
            "database tutorial"
        ],
        "about_name": "SQL Database Language",
        "isPartOf_name": "Backend Development Tutorial",
    },
    "postgresql": {
        "page_title": "PostgreSQL with Python: Databases, SQL and psycopg2",
        "page_description": "Learn PostgreSQL basics, how relational databases work with SQL, and how to connect Python applications using the psycopg2 database adapter.",
        "schema_type": "TechArticle",
        "slug": "postgresql",
        "section": "Backend",
        "keywords": [
            "PostgreSQL",
            "PostgreSQL database",
            "SQL database",
            "relational database",
            "Python PostgreSQL",
            "psycopg2",
            "Python database connection",
            "PostgreSQL queries",
            "SQL injection prevention",
            "backend development"
        ],
        "about_name": "PostgreSQL Database System",
        "isPartOf_name": "Backend Development Tutorial",
    },
    "orms": {
        "page_title": "Object Relational Mapping (ORM): Django ORM and SQLAlchemy Explained",
        "page_description": "Learn how object relational mapping works, how ORMs connect Python objects with databases, and the differences between Django ORM and SQLAlchemy.",
        "schema_type": "TechArticle",
        "slug": "orms",
        "section": "Backend",
        "keywords": [
            "ORM",
            "object relational mapping",
            "Python ORM",
            "Django ORM",
            "SQLAlchemy",
            "database abstraction",
            "Python databases",
            "relational databases",
            "SQL queries",
            "backend development"
        ],
        "about_name": "Object Relational Mapping",
        "isPartOf_name": "Backend Development Tutorial",
    },
    "sqlalchemy": {
        "page_title": "SQLAlchemy: Python Database Toolkit and ORM Explained",
        "page_description": "Learn SQLAlchemy with Python, including Expression Language, database connections, sessions, and class-based ORM models for working with relational databases.",
        "schema_type": "TechArticle",
        "slug": "sqlalchemy",
        "section": "Backend",
        "keywords": [
            "SQLAlchemy",
            "Python ORM",
            "SQLAlchemy ORM",
            "SQLAlchemy Expression Language",
            "Python database toolkit",
            "database sessions",
            "SQLAlchemy models",
            "relational databases",
            "Python PostgreSQL",
            "backend development"
        ],
        "about_name": "SQLAlchemy",
        "isPartOf_name": "Backend Development Tutorial",
    },
}