django_SEO = {
    "home": {
        "page_title": "Django Tutorial | MVT Architecture, Models, Views, Templates and Commands",
        "page_description": "Learn Django fundamentals including the MVT architecture, models, views, templates, common commands and how to build Python web applications.",
        "schema_type": "TechArticle",
        "slug": "home",
        "section": "Django",
        "keywords": [
            "Django",
            "Django tutorial",
            "Python Django",
            "Django framework",
            "Django MVT",
            "Django models",
            "Django views",
            "Django templates",
            "Django commands",
            "Django ORM",
            "Python web development",
            "web development"
        ],
        "about_name": "Django Introduction",
        "isPartOf_name": "Django Tutorial",
    },
    "getting-started-with-django": {
        "page_title": "Getting Started with Django | Installation, Virtual Environments and Migrations",
        "page_description": "Learn how to set up a Django project, create a virtual environment, install Django, run migrations, create a superuser and configure .gitignore files.",
        "schema_type": "TechArticle",
        "slug": "getting-started-with-django",
        "section": "Django",
        "keywords": [
            "getting started with Django",
            "Django installation",
            "install Django",
            "Django virtual environment",
            "Python virtual environment",
            "Django migrations",
            "Django superuser",
            "Django setup",
            "Django tutorial",
            "Django .gitignore",
            "Python web development",
            "web development"
        ],
        "about_name": "Getting Started with Django",
        "isPartOf_name": "Django Tutorial",
    },
    "admin": {
        "page_title": "Django Admin Tutorial | Superusers, Admin Interface and Model Management",
        "page_description": "Learn how to create a Django superuser, access the Django admin interface, manage users and customise how models are displayed in the admin panel.",
        "schema_type": "TechArticle",
        "slug": "admin",
        "section": "Django",
        "keywords": [
            "Django admin",
            "Django admin interface",
            "Django superuser",
            "createsuperuser",
            "Django admin panel",
            "Django models",
            "admin site",
            "Django tutorial",
            "Python web development",
            "web development"
        ],
        "about_name": "Django Admin",
        "isPartOf_name": "Django Tutorial",
    },
    "envpy": {
        "page_title": "Django env.py Tutorial | Environment Variables and Secret Keys",
        "page_description": "Learn how to create an env.py file, store environment variables securely, protect secret keys and configure sensitive settings in Django projects.",
        "schema_type": "TechArticle",
        "slug": "envpy",
        "section": "Django",
        "keywords": [
            "Django env.py",
            "Django environment variables",
            "env.py",
            "SECRET_KEY",
            "Django secret key",
            "Python environment variables",
            "Django security",
            "Django settings",
            "API keys",
            "Django tutorial",
            "web development"
        ],
        "about_name": "Django env.py",
        "isPartOf_name": "Django Tutorial",
    },
    "settings": {
        "page_title": "Django settings.py Tutorial | Configuration, Security and Project Settings",
        "page_description": "Learn how to configure Django settings.py, including security, databases, installed apps, middleware, templates, static files, Cloudinary, WhiteNoise and Heroku.",
        "schema_type": "TechArticle",
        "slug": "settings",
        "section": "Django",
        "keywords": [
            "Django settings.py",
            "settings.py",
            "Django configuration",
            "Django settings",
            "Django middleware",
            "Django installed apps",
            "Django templates",
            "Django static files",
            "Cloudinary Django",
            "WhiteNoise Django",
            "Heroku Django",
            "Django tutorial",
            "Python web development"
        ],
        "about_name": "Django settings.py",
        "isPartOf_name": "Django Tutorial",
    },
    "urls": {
        "page_title": "Django URLs Tutorial | URL Routing, urls.py, Paths and Views",
        "page_description": "Learn how Django URL routing works using project and app-level urls.py files, path(), include(), named URLs and views.",
        "schema_type": "TechArticle",
        "slug": "urls",
        "section": "Django",
        "keywords": [
            "Django URLs",
            "Django url routing",
            "urls.py",
            "Django path",
            "Django include",
            "Django URL dispatcher",
            "Django views",
            "named URLs",
            "Django tutorial",
            "Python web development",
            "web development"
        ],
        "about_name": "Django URL Routing",
        "isPartOf_name": "Django Tutorial",
    },
    "apps": {
        "page_title": "Django Apps Tutorial | Creating Apps, Project Structure and Core Apps",
        "page_description": "Learn how Django apps work, create reusable applications, structure templates, configure URLs and build a core app for shared functionality.",
        "schema_type": "TechArticle",
        "slug": "apps",
        "section": "Django",
        "keywords": [
            "Django apps",
            "create Django app",
            "Django startapp",
            "Django project structure",
            "Django core app",
            "Django templates",
            "Django URLs",
            "Django context processor",
            "reusable Django apps",
            "Django tutorial",
            "Python web development",
            "web development"
        ],
        "about_name": "Django Apps",
        "isPartOf_name": "Django Tutorial",
    },
    "templates": {
        "page_title": "Django Templates: Include, Extend, Template Inheritance and Structure",
        "page_description": "Learn Django templates including template inheritance, base templates, include and extends tags, global templates, app template structure and rendering templates from views.",
        "schema_type": "TechArticle",
        "slug": "templates",
        "section": "Django",
        "keywords": [
            "Django templates",
            "Django template language",
            "Django template inheritance",
            "Django base template",
            "Django include tag",
            "Django extends tag",
            "Django app templates",
            "Django template structure",
            "Django render templates",
            "Django views and templates",
            "Django tutorial",
            "Python web development",
        ],
        "about_name": "Django Templates",
        "isPartOf_name": "Django Tutorial",
    },
    "views": {
        "page_title": "Django Views: Functions, Rendering Templates, Context and Redirects",
        "page_description": "Learn Django views including view functions, handling HTTP requests, rendering templates, passing context data, returning responses, redirects and processing forms.",
        "schema_type": "TechArticle",
        "slug": "views",
        "section": "Django",
        "keywords": [
            "Django views",
            "Django view functions",
            "Django HTTP requests",
            "Django HTTP responses",
            "Django render function",
            "Django redirect function",
            "Django template rendering",
            "Django context",
            "Django forms processing",
            "Django views tutorial",
            "Python web development",
        ],
        "about_name": "Django Views",
        "isPartOf_name": "Django Tutorial",
    },
    "models": {
        "page_title": "Django Models and ORM: Fields, Migrations, Queries and Database Operations",
        "page_description": "Learn Django models and ORM including model fields, migrations, admin registration, database queries, filtering, CRUD operations and accessing data in views.",
        "schema_type": "TechArticle",
        "slug": "models",
        "section": "Django",
        "keywords": [
            "Django models",
            "Django ORM",
            "Django model fields",
            "Django database models",
            "Django migrations",
            "Django QuerySet",
            "Django database queries",
            "Django model relationships",
            "Django admin models",
            "Django CRUD operations",
            "Django tutorial",
            "Python web development",
        ],
        "about_name": "Django Models and ORM",
        "isPartOf_name": "Django Tutorial",
    },
    "forms": {
        "page_title": "Django Forms: ModelForms, Validation, Widgets and Handling User Input",
        "page_description": "Learn Django forms including ModelForms, form validation, widgets, CSRF protection, rendering forms in templates, handling submissions and saving user data.",
        "schema_type": "TechArticle",
        "slug": "forms",
        "section": "Django",
        "keywords": [
            "Django forms",
            "Django ModelForm",
            "Django form validation",
            "Django form widgets",
            "Django forms.py",
            "Django CSRF token",
            "Django form rendering",
            "Django form submission",
            "Django custom validation",
            "Django forms tutorial",
            "Python web development",
        ],
        "about_name": "Django Forms",
        "isPartOf_name": "Django Tutorial",
    },
    "templating-language": {
        "page_title": "Django Template Language: Syntax, Variables, Tags and Filters",
        "page_description": "Learn Django Template Language syntax including variables, loops, if statements, template tags, filters, inheritance and rendering dynamic HTML pages.",
        "schema_type": "TechArticle",
        "slug": "templating-language",
        "section": "Django",
        "keywords": [
            "Django Template Language",
            "Django template syntax",
            "Django template variables",
            "Django template tags",
            "Django template filters",
            "Django template inheritance",
            "Django template loops",
            "Django template if statements",
            "Django HTML rendering",
            "Django templates tutorial",
            "Python web development",
        ],
        "about_name": "Django Template Language",
        "isPartOf_name": "Django Tutorial",
    },
    "error-pages": {
        "page_title": "Django Error Pages: Custom 404, 500, 403 and 400 Templates",
        "page_description": "Learn how to create custom Django error pages including 404, 500, 403 and 400 templates, how Django loads them, and how to test error pages.",
        "schema_type": "TechArticle",
        "slug": "error-pages",
        "section": "Django",
        "keywords": [
            "Django error pages",
            "Django custom 404 page",
            "Django 404 template",
            "Django 500 error page",
            "Django 403 forbidden page",
            "Django 400 bad request",
            "Django templates",
            "Django error handling",
            "Django deployment",
            "Django tutorial",
            "Python web development",
        ],
        "about_name": "Django Error Pages",
        "isPartOf_name": "Django Tutorial",
    },
    "crud": {
        "page_title": "Django CRUD Operations: Create, Read, Update and Delete Records",
        "page_description": "Learn Django CRUD operations including creating, reading, updating and deleting database records using models, forms, views, templates and URLs.",
        "schema_type": "TechArticle",
        "slug": "crud",
        "section": "Django",
        "keywords": [
            "Django CRUD",
            "Django CRUD operations",
            "Django create read update delete",
            "Django create records",
            "Django read records",
            "Django update records",
            "Django delete records",
            "Django database operations",
            "Django forms and views",
            "Django ModelForm",
            "Django QuerySet",
            "Django tutorial",
        ],
        "about_name": "Django CRUD Operations",
        "isPartOf_name": "Django Tutorial",
    },
    "messages": {
        "page_title": "Django Messages Framework: Success, Error and Notification Messages",
        "page_description": "Learn Django messages framework including success, error and warning notifications, configuring message levels, adding messages in views and displaying them in templates.",
        "schema_type": "TechArticle",
        "slug": "messages",
        "section": "Django",
        "keywords": [
            "Django messages framework",
            "Django success messages",
            "Django error messages",
            "Django warning messages",
            "Django notifications",
            "Django messages in views",
            "Django messages template",
            "Django message levels",
            "Django Bootstrap alerts",
            "Django tutorial",
            "Python web development",
        ],
        "about_name": "Django Messages Framework",
        "isPartOf_name": "Django Tutorial",
    },
    "static": {
        "page_title": "Django Static Files: CSS, JavaScript, Media, Cloudinary and WhiteNoise",
        "page_description": "Learn Django static files including CSS, JavaScript, media folders, STATIC_URL, Cloudinary image hosting, and serving production files with WhiteNoise.",
        "schema_type": "TechArticle",
        "slug": "static",
        "section": "Django",
        "keywords": [
            "Django static files",
            "Django static folder",
            "Django STATIC_URL",
            "Django STATIC_ROOT",
            "Django media files",
            "Django CSS files",
            "Django JavaScript files",
            "Django Cloudinary",
            "Django WhiteNoise",
            "Django collectstatic",
            "Django deployment",
            "Django tutorial",
        ],
        "about_name": "Django Static Files",
        "isPartOf_name": "Django Tutorial",
    },
    "testing": {
        "page_title": "Django Testing Tutorial: TestCase, Views, Forms and Coverage",
        "page_description": "Learn Django testing with TestCase including testing views, forms, CRUD operations, assertions, test-driven development and measuring coverage with coverage.py.",
        "schema_type": "TechArticle",
        "slug": "testing",
        "section": "Django",
        "keywords": [
            "Django testing",
            "Django testing tutorial",
            "Django TestCase",
            "Django unit tests",
            "Django integration testing",
            "Django test views",
            "Django test forms",
            "Django CRUD testing",
            "Django assertions",
            "Django coverage.py",
            "Python testing",
            "Django tutorial",
        ],
        "about_name": "Django Testing",
        "isPartOf_name": "Django Tutorial",
    },
    "allauth": {
        "page_title": "Django Allauth Tutorial: User Registration, Login and Social Authentication",
        "page_description": "Learn how to use Django Allauth for user authentication including registration, login, password management, email verification and social account login.",
        "schema_type": "TechArticle",
        "slug": "allauth",
        "section": "Django",
        "keywords": [
            "Django Allauth",
            "Django authentication",
            "Django user registration",
            "Django login system",
            "Django social authentication",
            "Django accounts",
            "Django email verification",
            "Django authentication tutorial",
            "Python web authentication",
            "Django tutorial",
        ],
        "about_name": "Django Allauth Authentication",
        "isPartOf_name": "Django Tutorial",
    },
    "search": {
        "page_title": "Django Database Search and Algolia Search Integration",
        "page_description": (
            "Django Algolia Search Integration allows Django applications to add "
            "fast, scalable search functionality using Algolia's hosted search engine. "
            "Content from Django models, HTML templates, or external files can be "
            "indexed into Algolia records, allowing users to perform instant searches "
            "with features such as typo tolerance, relevance ranking, filtering, "
            "and custom search results."
        ),
        "schema_type": "TechArticle",
        "slug": "search",
        "section": "Django",
        "keywords": [
            "Django search",
            "Django Algolia",
            "Algolia API",
            "Django full text search",
            "Django website search",
            "Algolia indexing",
            "search engine integration",
            "Django search functionality",
            "Django searchable content",
            "Algolia Python client"
        ],
        "about_name": "Django Search and Algolia",
        "isPartOf_name": "Django Tutorial",
        },
    "languages": {
        "page_title": "Django Internationalization and Language Translation",
        "page_description": (
            "Django Languages provides internationalization (i18n) and translation "
            "functionality for multilingual web applications. Learn how to configure "
            "Django language settings, use GNU gettext, create translation files, "
            "translate views and templates, set up locale folders, add language "
            "switching URLs, and create user language dropdown menus."
        ),
        "schema_type": "TechArticle",
        "slug": "languages",
        "section": "Django",
        "keywords": [
            "Django languages",
            "Django internationalization",
            "Django i18n",
            "Django translation",
            "Django gettext",
            "GNU gettext Django",
            "Django locale files",
            "Django multilingual website",
            "Django language switcher",
            "Django translation files",
            "Django makemessages",
            "Django compilemessages",
            "Django language middleware"
        ],
        "about_name": "Django Languages and Internationalization",
        "isPartOf_name": "Django Tutorial",
    },
}