HTML_SEO = {
    "home": {
        "page_title": "Learn HTML: Elements, Attributes, Nesting, IDs, Classes and DOCTYPE",
        "page_description": "Learn HTML fundamentals including elements, nesting, attributes, IDs, classes, comments and the HTML5 DOCTYPE with practical examples for building webpages.",
        "schema_type": "TechArticle",
        "slug": "home",
        "section": "HTML",
        "keywords": [
            "HTML",
            "HTML tutorial",
            "HTML elements",
            "HTML attributes",
            "HTML nesting",
            "HTML tags",
            "HTML5 DOCTYPE",
            "HTML IDs and classes",
            "web development"
        ],
        "about_name": "HTML Introduction",
        "isPartOf_name": "HTML Tutorial",
    },
    "introducing-elements": {
        "page_title": "HTML Elements Explained: Structural, Block and Inline Elements",
        "page_description": "Learn about HTML elements including structural, block, inline and neutral elements, plus the purpose of the head and body elements in an HTML document.",
        "schema_type": "TechArticle",
        "slug": "introducing-elements",
        "section": "HTML",
        "keywords": [
            "HTML elements",
            "HTML tags",
            "HTML structure",
            "HTML structural elements",
            "block elements",
            "inline elements",
            "HTML head element",
            "HTML body element",
            "HTML tutorial"
        ],
        "about_name": "HTML Elements",
        "isPartOf_name": "HTML Tutorial",
    },
    "common-elements": {
        "page_title": "Common HTML Elements: Div, Span, Headings, Paragraphs and Text Formatting",
        "page_description": "Learn the most common HTML elements including div, span, headings, paragraphs, text formatting tags and breaking elements used to structure webpages.",
        "schema_type": "TechArticle",
        "slug": "common-elements",
        "section": "HTML",
        "keywords": [
            "HTML elements",
            "HTML tags",
            "common HTML tags",
            "div element",
            "span element",
            "HTML headings",
            "HTML paragraphs",
            "HTML text formatting",
            "HTML tutorial"
        ],
        "about_name": "Common HTML Elements",
        "isPartOf_name": "HTML Tutorial",
    },
    "lists": {
        "page_title": "HTML Lists: Ordered, Unordered and Description Lists",
        "page_description": "Learn how to create HTML lists using unordered lists, ordered lists and description lists, including nested lists with ul, ol, li, dl, dt and dd elements.",
        "schema_type": "TechArticle",
        "slug": "lists",
        "section": "HTML",
        "keywords": [
            "HTML lists",
            "unordered lists",
            "ordered lists",
            "description lists",
            "HTML ul element",
            "HTML ol element",
            "HTML li element",
            "nested HTML lists",
            "HTML tutorial"
        ],
        "about_name": "HTML Lists",
        "isPartOf_name": "HTML Tutorial",
    },
    "tables": {
        "page_title": "HTML Tables: Rows, Columns, thead, tbody, th and td",
        "page_description": "Learn how to create HTML tables using table, thead, tbody, tfoot, tr, th and td elements, including captions, colspan and rowspan attributes.",
        "schema_type": "TechArticle",
        "slug": "tables",
        "section": "HTML",
        "keywords": [
            "HTML tables",
            "HTML table element",
            "HTML table rows",
            "HTML table columns",
            "HTML thead tbody tfoot elements",
            "HTML th element",
            "HTML td element",
            "HTML colspan",
            "HTML rowspan",
            "HTML tutorial"
        ],
        "about_name": "HTML Tables",
        "isPartOf_name": "HTML Tutorial",
    },
    "forms": {
        "page_title": "HTML Forms: Input Types, GET and POST, Buttons and Validation",
        "page_description": "Learn how to create HTML forms using form, input, label, button and textarea elements, including GET and POST methods, input types and validation.",
        "schema_type": "TechArticle",
        "slug": "forms",
        "section": "HTML",
        "keywords": [
            "HTML forms",
            "HTML form element",
            "HTML input types",
            "HTML form validation",
            "HTML GET method",
            "HTML POST method",
            "HTML input element",
            "HTML label element",
            "HTML button element",
            "HTML textarea",
            "HTML tutorial"
        ],
        "about_name": "HTML Forms",
        "isPartOf_name": "HTML Tutorial",
    },
    "links": {
        "page_title": "HTML Links: Anchor Tags, href, target and Link Attributes",
        "page_description": "Learn how to create HTML links using the anchor tag, href attribute, absolute and relative URLs, email links, phone links and common link attributes.",
        "schema_type": "TechArticle",
        "slug": "links",
        "section": "HTML",
        "keywords": [
            "HTML links",
            "HTML anchor tag",
            "HTML href attribute",
            "HTML hyperlinks",
            "absolute and relative links",
            "HTML target attribute",
            "HTML rel attribute",
            "HTML mailto links",
            "HTML tel links",
            "HTML tutorial"
        ],
        "about_name": "HTML Links",
        "isPartOf_name": "HTML Tutorial",
    },
    "media": {
        "page_title": "HTML Media Elements: Images, Video and Audio",
        "page_description": "Learn how to add images, video and audio to HTML pages using img, video and audio elements, including attributes, file formats and accessibility tips.",
        "schema_type": "TechArticle",
        "slug": "media",
        "section": "HTML",
        "keywords": [
            "HTML media elements",
            "HTML images",
            "HTML img element",
            "HTML video element",
            "HTML audio element",
            "HTML image attributes",
            "HTML alt attribute",
            "HTML video controls",
            "HTML audio source",
            "HTML tutorial"
        ],
        "about_name": "HTML Media",
        "isPartOf_name": "HTML Tutorial",
    },
    "buttons": {
        "page_title": "HTML Buttons: Button Types, Submit, Reset and Attributes",
        "page_description": "Learn how to create HTML buttons using the button and input elements, including submit, reset and disabled button types with common attributes.",
        "schema_type": "TechArticle",
        "slug": "buttons",
        "section": "HTML",
        "keywords": [
            "HTML buttons",
            "HTML button element",
            "HTML button types",
            "HTML submit button",
            "HTML reset button",
            "HTML input button",
            "HTML disabled attribute",
            "HTML forms",
            "HTML tutorial"
        ],
        "about_name": "HTML Buttons",
        "isPartOf_name": "HTML Tutorial",
    },
    "semantic-html": {
        "page_title": "Semantic HTML: Elements, Accessibility and SEO Benefits",
        "page_description": "Learn semantic HTML elements including header, nav, main, section, article, aside, figure and details to improve accessibility, structure and SEO.",
        "schema_type": "TechArticle",
        "slug": "semantic",
        "section": "HTML",
        "keywords": [
            "semantic HTML",
            "HTML semantic elements",
            "HTML accessibility",
            "semantic HTML5",
            "HTML header element",
            "HTML nav element",
            "HTML article element",
            "HTML section element",
            "HTML SEO",
            "HTML tutorial"
        ],
        "about_name": "Semantic HTML",
        "isPartOf_name": "HTML Tutorial",
    },
    "html-accessibility-validation": {
        "page_title": "HTML Accessibility and Validation: ARIA Labels, Standards and Best Practices",
        "page_description": "Learn HTML accessibility techniques including ARIA labels, accessible attributes and validating HTML with W3C standards for better usability and SEO.",
        "schema_type": "TechArticle",
        "slug": "accessibility",
        "section": "HTML",
        "keywords": [
            "HTML accessibility",
            "HTML validation",
            "ARIA labels",
            "HTML ARIA attributes",
            "accessible HTML",
            "W3C HTML validator",
            "HTML standards",
            "HTML SEO",
            "screen readers HTML",
            "HTML tutorial"
        ],
        "about_name": "HTML Accessibility and Validation",
        "isPartOf_name": "HTML Tutorial",
    },
    "html-example": {
        "page_title": "HTML Example: Complete HTML5 Page Template and Boilerplate",
        "page_description": "Explore a complete HTML5 example template including document structure, metadata, semantic elements, navigation, media, and accessibility features.",
        "schema_type": "TechArticle",
        "slug": "example",
        "section": "HTML",
        "keywords": [
            "HTML example",
            "HTML template",
            "HTML5 boilerplate",
            "basic HTML page",
            "HTML document structure",
            "HTML starter template",
            "semantic HTML example",
            "HTML head element",
            "HTML accessibility",
            "HTML tutorial"
        ],
        "about_name": "HTML5 Document Structure Example",
        "isPartOf_name": "HTML Tutorial",
    },
}