python_SEO = {
"home": {
    "page_title": "Learn Python: Syntax, Setup, Libraries and OOP Basics",
    "page_description": "Learn Python programming fundamentals including installation, syntax, file structure, running code, libraries, debugging, and object-oriented programming.",
    "schema_type": "TechArticle",
    "slug": "home",
    "section": "Python",
    "keywords": [
        "Python programming",
        "Python tutorial",
        "Python syntax",
        "Python installation",
        "Python setup",
        "Python file structure",
        "Running Python scripts",
        "Python libraries",
        "Python pip",
        "Python debugging",
        "Python object oriented programming",
        "Python classes and objects",
        "web development",
        "programming tutorial"
    ],
    "about_name": "Python Programming Introduction",
    "isPartOf_name": "Python Tutorial",
},
"variables": {
    "page_title": "Python Variables: Assignment, Scope and Data Types",
    "page_description": "Learn Python variables including assignment, naming rules, multiple variables, scope, mutable and immutable objects, and variable references.",
    "schema_type": "TechArticle",
    "slug": "variables",
    "section": "Python",
    "keywords": [
        "Python variables",
        "Python variable assignment",
        "Python variable naming",
        "Python snake case",
        "Python variable scope",
        "Python local variables",
        "Python global variables",
        "Python nonlocal variables",
        "Python mutable objects",
        "Python immutable objects",
        "Python variable references",
        "Python tutorial",
        "programming tutorial"
    ],
    "about_name": "Python Variables",
    "isPartOf_name": "Python Tutorial",
},
"scope": {
    "page_title": "Python Scope: LEGB Rule, Global, Local and Nonlocal",
    "page_description": "Learn Python variable scope including the LEGB rule, local and global variables, enclosing scope, and using nonlocal in nested functions.",
    "schema_type": "TechArticle",
    "slug": "scope",
    "section": "Python",
    "keywords": [
        "Python scope",
        "Python LEGB rule",
        "Python local scope",
        "Python global scope",
        "Python enclosing scope",
        "Python nonlocal keyword",
        "Python variable scope",
        "Python nested functions",
        "Python global variables",
        "Python local variables",
        "Python functions",
        "Python tutorial",
        "programming tutorial"
    ],
    "about_name": "Python Variable Scope",
    "isPartOf_name": "Python Tutorial",
},
"loops": {
    "page_title": "Python Loops: For, While, Range and Loop Control",
    "page_description": "Learn Python loops including for loops, while loops, range(), break, continue, pass, flags, and controlling repeated code execution.",
    "schema_type": "TechArticle",
    "slug": "loops",
    "section": "Python",
    "keywords": [
        "Python loops",
        "Python for loops",
        "Python while loops",
        "Python range function",
        "Python loop control",
        "Python break statement",
        "Python continue statement",
        "Python pass statement",
        "Python flags",
        "Python iteration",
        "Python programming basics",
        "Python tutorial",
        "programming tutorial"
    ],
    "about_name": "Python Loops",
    "isPartOf_name": "Python Tutorial",
},
"conditionals": {
    "page_title": "Python Conditionals: If, Elif, Else and Logic Operators",
    "page_description": "Learn Python conditionals including if statements, elif, else, logical operators, truthy and falsy values, and the walrus operator.",
    "schema_type": "TechArticle",
    "slug": "conditionals",
    "section": "Python",
    "keywords": [
        "Python conditionals",
        "Python if statement",
        "Python elif statement",
        "Python else statement",
        "Python logical operators",
        "Python truthy and falsy values",
        "Python walrus operator",
        "Python comparison operators",
        "Python decision making",
        "Python control flow",
        "Python programming basics",
        "Python tutorial",
        "programming tutorial"
    ],
    "about_name": "Python Conditional Statements",
    "isPartOf_name": "Python Tutorial",
},
"data-types": {
    "page_title": "Python Data Types, Type Conversion and Operators",
    "page_description": "Learn Python data types including integers, floats, lists, tuples, strings, dictionaries, sets, type conversion functions and Python operators.",
    "schema_type": "TechArticle",
    "slug": "data-types",
    "section": "Python",
    "keywords": [
        "Python data types",
        "Python types",
        "Python int",
        "Python float",
        "Python list",
        "Python tuple",
        "Python string",
        "Python dictionary",
        "Python set",
        "Python type conversion",
        "Python casting",
        "Python operators",
        "Python arithmetic operators",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Data Types and Operators",
    "isPartOf_name": "Python Tutorial",
},
"strings": {
    "page_title": "Python Strings: Methods, Formatting, Slicing and Operations",
    "page_description": "Learn Python strings including string creation, concatenation, f-strings, slicing, methods, searching, replacing, formatting, encoding and validation.",
    "schema_type": "TechArticle",
    "slug": "strings",
    "section": "Python",
    "keywords": [
        "Python strings",
        "Python string methods",
        "Python string formatting",
        "Python f strings",
        "Python string concatenation",
        "Python string slicing",
        "Python string indexing",
        "Python string operations",
        "Python string manipulation",
        "Python Unicode strings",
        "Python string replace",
        "Python string split",
        "Python string join",
        "Python string encoding",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Strings",
    "isPartOf_name": "Python Tutorial",
},
"booleans": {
    "page_title": "Python Booleans: True, False, Operators and Logic",
    "page_description": "Learn Python booleans including True and False values, boolean operators, identity operators, membership operators and truth value testing.",
    "schema_type": "TechArticle",
    "slug": "booleans",
    "section": "Python",
    "keywords": [
        "Python booleans",
        "Python True and False",
        "Python bool function",
        "Python boolean operators",
        "Python and operator",
        "Python or operator",
        "Python not operator",
        "Python identity operators",
        "Python is operator",
        "Python is not operator",
        "Python membership operators",
        "Python in operator",
        "Python not in operator",
        "Python truthy values",
        "Python falsy values",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Booleans and Logical Operators",
    "isPartOf_name": "Python Tutorial",
},
"lists": {
    "page_title": "Python Lists: Methods, Slicing, Loops and Operations",
    "page_description": "Learn Python lists including creating lists, accessing elements, slicing, joining, copying, looping, list comprehensions and built-in list methods.",
    "schema_type": "TechArticle",
    "slug": "lists",
    "section": "Python",
    "keywords": [
        "Python lists",
        "Python list methods",
        "Python list operations",
        "Python list indexing",
        "Python list slicing",
        "Python list comprehension",
        "Python loops",
        "Python for loop",
        "Python append",
        "Python extend",
        "Python remove",
        "Python sort",
        "Python copy lists",
        "Python join lists",
        "Python zip function",
        "Python range function",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Lists and List Methods",
    "isPartOf_name": "Python Tutorial",
},
"tuples": {
    "page_title": "Python Tuples: Immutable Collections, Unpacking and Methods",
    "page_description": "Learn Python tuples including creating tuples, accessing items, tuple unpacking, nesting, immutability, hashability and built-in tuple methods.",
    "schema_type": "TechArticle",
    "slug": "tuples",
    "section": "Python",
    "keywords": [
        "Python tuples",
        "Python tuple methods",
        "Python immutable data types",
        "Python tuple unpacking",
        "Python tuple indexing",
        "Python tuple slicing",
        "Python nested tuples",
        "Python hashable objects",
        "Python tuple count",
        "Python tuple index",
        "Python lists vs tuples",
        "Python collections",
        "Python data structures",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Tuples and Tuple Methods",
    "isPartOf_name": "Python Tutorial",
},
"dictionaries": {
    "page_title": "Python Dictionaries: Keys, Values, Methods and Comprehension",
    "page_description": "Learn Python dictionaries including key-value pairs, accessing values, combining lists, looping, dictionary comprehension and built-in methods.",
    "schema_type": "TechArticle",
    "slug": "dictionaries",
    "section": "Python",
    "keywords": [
        "Python dictionaries",
        "Python dictionary methods",
        "Python key value pairs",
        "Python dictionary keys",
        "Python dictionary values",
        "Python dictionary update",
        "Python dictionary get",
        "Python dictionary items",
        "Python dictionary loops",
        "Python dictionary comprehension",
        "Python zip function",
        "Python data structures",
        "Python dictionaries vs JavaScript objects",
        "Python collections",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Dictionaries and Dictionary Methods",
    "isPartOf_name": "Python Tutorial",
},
"sets": {
    "page_title": "Python Sets: Unique Values, Operations and Frozensets",
    "page_description": "Learn Python sets including unique collections, removing duplicates, set operations, membership testing, hashability and immutable frozensets.",
    "schema_type": "TechArticle",
    "slug": "sets",
    "section": "Python",
    "keywords": [
        "Python sets",
        "Python set methods",
        "Python set operations",
        "Python union",
        "Python intersection",
        "Python difference",
        "Python symmetric difference",
        "Python remove duplicates",
        "Python membership testing",
        "Python hashable objects",
        "Python frozenset",
        "Python immutable sets",
        "Python data structures",
        "Python collections",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Sets and Set Operations",
    "isPartOf_name": "Python Tutorial",
},
"classes": {
    "page_title": "Python Classes: OOP, Objects, Inheritance and Methods",
    "page_description": "Learn Python classes and object-oriented programming including objects, attributes, methods, inheritance, getters, setters, __str__, composition and mixins.",
    "schema_type": "TechArticle",
    "slug": "classes",
    "section": "Python",
    "keywords": [
        "Python classes",
        "Python object oriented programming",
        "Python OOP",
        "Python objects",
        "Python class methods",
        "Python attributes",
        "Python __init__ method",
        "Python self keyword",
        "Python class inheritance",
        "Python super function",
        "Python getters and setters",
        "Python __str__ method",
        "Python composition",
        "Python multiple inheritance",
        "Python mixins",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Classes and Object-Oriented Programming",
    "isPartOf_name": "Python Tutorial",
},
"regular-expressions": {
    "page_title": "Python Regular Expressions: Regex Patterns and re Module",
    "page_description": "Learn Python regular expressions including regex patterns, character sets, groups, anchors, special sequences and using the Python re module.",
    "schema_type": "TechArticle",
    "slug": "regular-expressions",
    "section": "Python",
    "keywords": [
        "Python regular expressions",
        "Python regex",
        "Python re module",
        "Python regex patterns",
        "Python regex functions",
        "Python re search",
        "Python re match",
        "Python re fullmatch",
        "Python re findall",
        "Python re split",
        "Python re sub",
        "Python regex character sets",
        "Python regex groups",
        "Python regex anchors",
        "Python regex special sequences",
        "Python raw strings",
        "Python string matching",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Regular Expressions and Regex Patterns",
    "isPartOf_name": "Python Tutorial",
},
"functions": {
    "page_title": "Python Functions: Parameters, Returns, Decorators and More",
    "page_description": "Learn Python functions including defining functions, parameters, arguments, docstrings, return values, decorators, built-in functions and first-class functions.",
    "schema_type": "TechArticle",
    "slug": "functions",
    "section": "Python",
    "keywords": [
        "Python functions",
        "Python function definition",
        "Python function parameters",
        "Python function arguments",
        "Python default arguments",
        "Python args kwargs",
        "Python docstrings",
        "Python return statement",
        "Python first class functions",
        "Python function variables",
        "Python decorators",
        "Python built in functions",
        "Python type function",
        "Python pprint",
        "Python programming concepts",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Functions and Function Concepts",
    "isPartOf_name": "Python Tutorial",
},
"input": {
    "page_title": "Python Input: User Input, Prompts and Match Statements",
    "page_description": "Learn Python input including collecting user responses, creating prompts, processing input values and using match statements for control flow.",
    "schema_type": "TechArticle",
    "slug": "input",
    "section": "Python",
    "keywords": [
        "Python input",
        "Python input function",
        "Python user input",
        "Python prompts",
        "Python terminal input",
        "Python input variables",
        "Python string input",
        "Python match statement",
        "Python case statement",
        "Python pattern matching",
        "Python control flow",
        "Python if elif else",
        "Python 3.10 match",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python User Input and Match Statements",
    "isPartOf_name": "Python Tutorial",
},
"os": {
    "page_title": "Python OS Module: Files, Paths and System Operations",
    "page_description": "Learn Python os and sys modules including working with files, directories, paths, command-line arguments and controlling program execution.",
    "schema_type": "TechArticle",
    "slug": "os",
    "section": "Python",
    "keywords": [
        "Python os module",
        "Python sys module",
        "Python file system",
        "Python working directory",
        "Python os.getcwd",
        "Python os.listdir",
        "Python os.path.join",
        "Python os.path.split",
        "Python os.path.splitext",
        "Python file paths",
        "Python directories",
        "Python command line arguments",
        "Python sys.argv",
        "Python sys.exit",
        "Python standard library",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python OS and System Modules",
    "isPartOf_name": "Python Tutorial",
},
"math": {
    "page_title": "Python Math Module: Functions, Statistics and Random",
    "page_description": "Learn Python math, statistics and random modules including mathematical functions, constants, data analysis tools and random number generation.",
    "schema_type": "TechArticle",
    "slug": "math",
    "section": "Python",
    "keywords": [
        "Python math module",
        "Python mathematics",
        "Python math functions",
        "Python math constants",
        "Python statistics module",
        "Python mean",
        "Python median",
        "Python mode",
        "Python standard deviation",
        "Python random module",
        "Python random numbers",
        "Python random choice",
        "Python random shuffle",
        "Python randint",
        "Python numerical calculations",
        "Python standard library",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Math, Statistics and Random Modules",
    "isPartOf_name": "Python Tutorial",
},
"datetime": {
    "page_title": "Python Datetime: Dates, Times and Date Manipulation",
    "page_description": "Learn Python datetime including creating dates, accessing time information, formatting dates, parsing strings and working with dateutil.",
    "schema_type": "TechArticle",
    "slug": "datetime",
    "section": "Python",
    "keywords": [
        "Python datetime",
        "Python date and time",
        "Python datetime module",
        "Python datetime now",
        "Python date objects",
        "Python time objects",
        "Python strftime",
        "Python date formatting",
        "Python date parsing",
        "Python dateutil",
        "Python parser",
        "Python time manipulation",
        "Python standard library",
        "Python libraries",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Datetime and Date Manipulation",
    "isPartOf_name": "Python Tutorial",
},
"pandas": {
    "page_title": "Python Pandas: DataFrames, Data Analysis and Cleaning",
    "page_description": "Learn Python Pandas for data analysis including DataFrames, loading data, filtering, sorting, editing columns, grouping and saving datasets.",
    "schema_type": "TechArticle",
    "slug": "pandas",
    "section": "Python",
    "keywords": [
        "Python pandas",
        "Python DataFrame",
        "Pandas tutorial",
        "Python data analysis",
        "Python data cleaning",
        "Pandas CSV",
        "Pandas Excel",
        "Pandas read_csv",
        "Pandas read_excel",
        "Pandas filtering",
        "Pandas sorting",
        "Pandas columns",
        "Pandas indexing",
        "Pandas groupby",
        "Pandas saving data",
        "Pandas string filtering",
        "Python data science",
        "Python libraries",
        "Python tutorial"
    ],
    "about_name": "Python Pandas Data Analysis Library",
    "isPartOf_name": "Python Tutorial",
},
"numpy": {
    "page_title": "Python NumPy: Arrays, Mathematics and Data Computing",
    "page_description": "Learn Python NumPy including arrays, dimensions, loading data, array operations, reshaping, indexing, boolean masking and numerical computing.",
    "schema_type": "TechArticle",
    "slug": "numpy",
    "section": "Python",
    "keywords": [
        "Python NumPy",
        "NumPy arrays",
        "Python numerical computing",
        "NumPy tutorial",
        "NumPy dimensions",
        "NumPy array operations",
        "NumPy mathematical functions",
        "NumPy indexing",
        "NumPy slicing",
        "NumPy boolean masking",
        "NumPy reshape",
        "NumPy stacking",
        "NumPy random functions",
        "NumPy binomial distribution",
        "Python data science",
        "Python scientific computing",
        "Python libraries",
        "Python tutorial"
    ],
    "about_name": "Python NumPy Numerical Computing Library",
    "isPartOf_name": "Python Tutorial",
},
"csv": {
    "page_title": "Python CSV Files: Reading, Writing and Processing Data",
    "page_description": "Learn Python CSV handling including reading files, DictReader, writing CSV data, delimiters, extracting columns and using the built-in csv module.",
    "schema_type": "TechArticle",
    "slug": "csv",
    "section": "Python",
    "keywords": [
        "Python CSV",
        "Python csv module",
        "Python read CSV",
        "Python write CSV",
        "Python DictReader",
        "Python DictWriter",
        "Python csv reader",
        "Python csv writer",
        "Python CSV files",
        "Python delimiter",
        "Python data processing",
        "Python file handling",
        "Python tabular data",
        "Python data analysis",
        "Python standard library",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python CSV File Handling",
    "isPartOf_name": "Python Tutorial",
},
"json": {
    "page_title": "Python JSON: Reading, Writing and Data Conversion",
    "page_description": "Learn Python JSON handling including loading files, writing JSON data, converting strings, formatting output, encoding and Python to JSON types.",
    "schema_type": "TechArticle",
    "slug": "json",
    "section": "Python",
    "keywords": [
        "Python JSON",
        "Python json module",
        "Python read JSON",
        "Python write JSON",
        "Python json load",
        "Python json dump",
        "Python json loads",
        "Python json dumps",
        "Python JSON files",
        "Python JSON strings",
        "Python data conversion",
        "Python Unicode encoding",
        "Python JSON errors",
        "Python dictionaries",
        "Python lists",
        "Python data formats",
        "Python standard library",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python JSON File Handling and Data Conversion",
    "isPartOf_name": "Python Tutorial",
},
"pillow": {
    "page_title": "Python Pillow: Image Editing, Processing and Manipulation",
    "page_description": "Learn Python Pillow for image processing including opening, editing, resizing, drawing, saving and manipulating images with the PIL library.",
    "schema_type": "TechArticle",
    "slug": "pillow",
    "section": "Python",
    "keywords": [
        "Python Pillow",
        "Python image processing",
        "Python PIL",
        "Pillow tutorial",
        "Python image editing",
        "Python open images",
        "Python resize images",
        "Python crop images",
        "Python rotate images",
        "Python draw images",
        "Python save images",
        "Python image pixels",
        "Python RGB images",
        "Python RGBA images",
        "Python image manipulation",
        "Python libraries",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Pillow Image Processing Library",
    "isPartOf_name": "Python Tutorial",
},
"unit-testing": {
    "page_title": "Python Unit Testing: Pytest, Errors and Exceptions",
    "page_description": "Learn Python unit testing with pytest, assertions, exception handling, custom errors, runtime errors and managing failures in your code.",
    "schema_type": "TechArticle",
    "slug": "unit-testing",
    "section": "Python",
    "keywords": [
        "Python unit testing",
        "Python pytest",
        "Pytest tutorial",
        "Python test functions",
        "Python assert",
        "Python assertions",
        "Python exceptions",
        "Python error handling",
        "Python try except",
        "Python finally",
        "Python custom errors",
        "Python raise exception",
        "Python runtime errors",
        "Python debugging",
        "Python testing framework",
        "Python software testing",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Unit Testing and Exception Handling",
    "isPartOf_name": "Python Tutorial",
},
"data-and-api-requests": {
    "page_title": "Python Data Files and API Requests: CSV, JSON and APIs",
    "page_description": "Learn Python data handling including reading files, CSV processing, API requests, data collection and connecting to external data sources.",
    "schema_type": "TechArticle",
    "slug": "data-and-api-requests",
    "section": "Python",
    "keywords": [
        "Python data handling",
        "Python file handling",
        "Python read files",
        "Python write files",
        "Python CSV files",
        "Python API requests",
        "Python requests library",
        "Python REST APIs",
        "Python JSON data",
        "Python data collection",
        "Python datasets",
        "Python Google Sheets API",
        "Python gspread",
        "Python open function",
        "Python external data",
        "Python data analysis",
        "Python libraries",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Data Handling and API Requests",
    "isPartOf_name": "Python Tutorial",
},
"code-validation": {
    "page_title": "Python Code Validation: Flake8, Black and isort",
    "page_description": "Learn Python code validation with Flake8, Black and isort for formatting, PEP8 compliance, import organisation and cleaner code.",
    "schema_type": "TechArticle",
    "slug": "code-validation",
    "section": "Python",
    "keywords": [
        "Python code validation",
        "Python linting",
        "Python PEP8",
        "Python style guide",
        "Python Flake8",
        "Python Black formatter",
        "Python isort",
        "Python code formatting",
        "Python code quality",
        "Python syntax checking",
        "Python unused imports",
        "Python import sorting",
        "Python best practices",
        "Python development tools",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Code Validation and Formatting Tools",
    "isPartOf_name": "Python Tutorial",
},
"google-sheets-program": {
    "page_title": "Python Google Sheets API: Automate Sheets with gspread",
    "page_description": "Learn how to use Python with Google Sheets API and gspread to authenticate, validate data, update worksheets and automate spreadsheets.",
    "schema_type": "TechArticle",
    "slug": "google-sheets-program",
    "section": "Python",
    "keywords": [
        "Python Google Sheets API",
        "Python gspread",
        "Python Google Sheets automation",
        "Python spreadsheet automation",
        "Python Google Drive API",
        "Python service account credentials",
        "Python API authentication",
        "Python update Google Sheets",
        "Python append rows",
        "Python data validation",
        "Python spreadsheet projects",
        "Python credentials security",
        "Python gitignore",
        "Python automation scripts",
        "Python tutorial",
        "programming fundamentals"
    ],
    "about_name": "Python Google Sheets API Automation",
    "isPartOf_name": "Python Tutorial",
},
}