from django.urls import path
from . import views


urlpatterns = [
    path(
        '',
        views.python_home,
        name="python_home"
    ),
    path(
        'variables/',
        views.python_variables,
        name="python_variables"
    ),
    path(
        'data_types/',
        views.python_data_types,
        name="python_data_types"
    ),
    path(
        'strings/',
        views.python_strings,
        name="python_strings"
    ),
    path(
        'booleans/',
        views.python_booleans,
        name="python_booleans"
    ),
    path(
        'lists/',
        views.python_lists,
        name="python_lists"
    ),
    path(
        'tuples/',
        views.python_tuples,
        name="python_tuples"
    ),
    path(
        'dictionaries/',
        views.python_dictionaries,
        name="python_dictionaries"
    ),
    path(
        'sets/',
        views.python_sets,
        name="python_sets"
    ),
    path(
        'regular_expressions/',
        views.python_regular_expressions,
        name="python_regular_expressions"
    ),
    path(
        'functions/',
        views.python_functions,
        name="python_functions"
    ),
    path(
        'input/',
        views.python_input,
        name="python_input"
    ),
    path(
        'os/',
        views.python_os,
        name="python_os"
    ),
    path(
        'math/',
        views.python_math,
        name="python_math"
    ),
    path(
        'datetime/',
        views.python_datetime,
        name="python_datetime"
    ),
    path(
        'pandas/',
        views.python_pandas,
        name="python_pandas"
    ),
    path(
        'numpy/',
        views.python_numpy,
        name="python_numpy"
    ),
    path(
        'csv/',
        views.python_csv,
        name="python_csv"
    ),
    path(
        'json/',
        views.python_json,
        name="python_json"
    ),
    path(
        'pillow/',
        views.python_pillow,
        name="python_pillow"
    ),
    path(
        'scope/',
        views.python_scope,
        name="python_scope"
    ),
    path(
        'loops/',
        views.python_loops,
        name="python_loops"
    ),
    path(
        'conditionals/',
        views.python_conditionals,
        name="python_conditionals"
    ),
    path(
        'classes/',
        views.python_classes,
        name="python_classes"
    ),
    path(
        'unit_testing/',
        views.python_unit_testing,
        name="python_unit_testing"
    ),
    path(
        'data_and_api_requests/',
        views.python_data_and_api_requests,
        name="python_data_and_api_requests"
    ),
    path(
        'code_validation/',
        views.python_code_validation,
        name="python_code_validation"
    ),
]
